exports.filterParamsCource =[
{
  name : "language",
  values : [ "English",
            "Hindi",
            "Assamese",
            "Bengali",
            "Gujarati",
            "Kannada",
            "Malayalam",
            "Marathi",
            "Nepali",
            "Odia",
            "Punjabi",
            "Tamil",
            "Telugu",
            "Urdu",
            "Sanskrit",
            "Maithili",
            "Munda",
            "Santali",
            "Juang",
            "Ho",
            "Other" ]

},
{
  name : "subject",
  values : [ "Maths",
            "English",
            "Hindi",
            "Assamese",
            "Bengali",
            "Gujarati",
            "Kannada",
            "Malayalam",
            "Marathi",
            "Nepali",
            "Odia",
            "Punjabi",
            "Tamil",
            "Telugu",
            "Urdu",
            "Other", ]
             
},
{
  name : "medium",
  values : [ "English",
            "Hindi",
            "Assamese",
            "Bengali",
            "Gujarati",
            "Kannada",
            "Malayalam",
            "Marathi",
            "Nepali",
            "Odia",
            "Punjabi",
            "Tamil",
            "Telugu",
            "Urdu",
            "Other"  ]
             
}];
