const objectAssign = require('object-assign');
const stringsRes = {
	"en_US" : {
		ALREADY_HAVE_ACC : "Already have an Account? Sign in now",
		APPLY_FILTER : "APPLY FILTER",
		AS_FILE : "As File",
		AS_LINK : "As Link",
		BACK_TO_EXIT : "Press back again to exit app",
		CANCEL_DOWNLOAD : "CANCEL DOWNLOAD",
		COMING_SOON : "Coming soon..",
		COMMUNITIES : "Communities",
		CONFIRM : "Confirm",
		COURSE : "COURSE",
		COURSE_ENROLLED : "Course enrolled",
		COURSE_PROGRESS_COMPLETED : "%s % done",
		CONTENT_FLAGGED_MSG : "Content flagged successfully",
		CONTENT_FLAG_FAIL : "Content flagging failed",
		COURSES_BNAV : "COURSES",
		COURSES_IN_PROGRESS : "Courses In Progress",
		COURSES_LW : "Courses",
		CREATED_BY : "CREATED BY",
		CREATED_BY_SMALL : "Created by",
		DELETE : "Delete",
		DESCRIPTION : "Description",
		DOWNLOAD : "DOWNLOAD",
		DOWNLOADS : "downloads",
		EDIT : "Edit",
		EMAIL_ID : "EMAIL ID",
		EMPTY_SEARCH_RESULTS : "No Search Results Found",
		ENROLL_COURSE : "ENROLL THIS COURSE",
		ERROR_CONTENT_NOT_AVAILABLE : "Content not available",
		ERROR_CONTENT_NOT_FOUND : "Contents not added yet",
		ERROR_DURATION_NOT_AVAILABLE : "Duration not available",
		ERROR_EMAIL_FORMAT : "Email format not correct",
		ERROR_EMPTY_EMAIL : "Please enter the email",
		ERROR_EMPTY_FIRSTNAME : "Please enter the name",
		ERROR_EMPTY_LANGUAGE : "Please choose atleast one language",
		ERROR_EMPTY_MOBILE : "Please enter the mobile number",
		ERROR_EMPTY_PASSWORD : "Please enter the password",
		ERROR_EMPTY_USERNAME : "Please enter the user name",
		ERROR_FETCHING_DATA : "Error Fetching Data",
		ERROR_NO_COURSES_ENROLLED : "No Courses enrolled yet",
		ERROR_OFFLINE_MODE : "You’re not connected to the internet.",
		ERROR_NO_OFFLINE_RESOURCE : "No offline resource yet",
		ERROR_SERVER_CONNECTION : "Unable to connect to server",
		ERROR_SERVER_MESSAGE : "Error :",
		ERROR_SHORT_MOBILE : "Please check the mobile number format",
		ERROR_SHORT_PASSWORD : "Password cannot be shorter than 8 characters",
		FETCHING_CONTENTS : "Fetching Contents : %s %",
		FILE_SIZE : "Size [%s]",
		FILTER : "Filter",
		FILTER_BY : "FILTER BY",
		FIRST_NAME : "FIRST NAME",
		FIRST_NAME_HINT : "Enter your first name",
		GROUPS : "Groups",
		GROUPS_BNAV : "GROUPS",
		HINT_EMAIL_ID : "sample@test.com",
		HINT_LANGUAGE : "Choose preffered language",
		HINT_MOBILE_NUMBER : "Enter mobile number",
		HINT_PASSWORD : "Minimum 8 character password",
		HINT_USER_NAME : "Enter user name",
		HOME_BNAV : "HOME",
		JOIN : "JOIN",
		LATEST_COURSES : "Latest Courses",
		LOADING_CONTENT : "Loading content",
		LOGGED_OUT : "Logged out",
		MOBILE_NUMBER : "MOBILE NUMBER",
		MODULE_SIZE : "Module Size %s",
		MODULE_SIZE_UNAVAILABLE : "Module Size Unavailable",
		NEW : "New",
		NO_ACC_YET : "No Account yet? Sign up now",
		NO_PREVIEW : "No preview available",
		NUMBER_OF_VOTES : "Number of votes",
		OPEN : "OPEN",
		PASSWORD : "PASSWORD",
		PHONE : "PHONE",
		PLAY : "PLAY",
		POPULAR_COURSES : "Popular Courses",
		PREVIEWS : "PREVIEWS",
		PROFILE_BNAV : "PROFILE",
		PROFILE_DETAILS_TITLE : "Profile Details",
		PROFILE_LW : "Profile",
		PUBLISHED_DATE : "Published date",
		QUIZ : "QUIZ",
		RESOURCES_BNAV : "LIBRARY",
		RESOURCES_LW : "Library",
		RESUME : "RESUME",
		RETRY_ACTION : "Please retry",
		SAVED_ON : "Saved on",
		SAVED_RESOURCES : "Your saved items",
		SEARCH_HINT : "Search",
		SELECT : "SELECT",
		SELECT_A_REASON : "SELECT A REASON",
		SHARE_THIS : "Share this",
		SIGN_IN : "SIGN IN",
		SIGN_UP : "SIGN UP",
		SORT_BY : "SORT BY",
		STRUCTURE : "Structure",
		TO_DO : "To-Do",
		USER_NAME : "USER NAME",
		VIEW_ALL : "VIEW ALL",
		VIEW_ALL_COMMUNITIES : "Viewing all communities you’re a part of",
		VIEW_MORE : "VIEW MORE",
		WAIT_REQUEST : "Please Wait ...",
		WELCOME_BACK : "WELCOME BACK %s",
		WELCOME_M1 : "Welcome to %s",
		WELCOME_M2 : "Structured education for the educators",
		WELCOME_ON_BOARD : "Welcome to %s, %s ",
		WHAT_WENT_WRONG : "What went wrong?",
		YOUR_PROGRESS : "Your Progress: %s%",
		FLAG : "Flag / Report ",
		ERROR_EMPTY_RESULT : "No result available",
		ERROR_FLAG_CONTENT_MIN_REASON : "Please select atleast one reason for flag the content",
		ERROR_INVALID_EMAIL : "Invalid Email Id",
		MSG_RESOURCE_DELETED : "Content deleted from device",
		LOGOUT : "Logout",
		CREATOR_NAME_NOT_AVAILABLE : "Creator name not available",
		ENROLL : "ENROLL",
		VIEW_ONGOING_BATCHES : "View ongoing batches",
		VIEW_UPCOMING_BATCHES : "View upcoming batches",
		USER_NAME_PROFILE : "User Name",
		BATCHES_FOR_THIS_COURSE : "Batches for this course",
		ERROR_EMPTY_FIELDS : "Please enter the detials. ",
		INVALID_CONTENT : "Invalid Content",
		TIME_OUT : "Server timeout, please try again later",
		OPTIONAL : "(Optional)",
		PERCENTAGE : "Percentage",
		SUBJECTS : "Subjects",
		FROM : "From",
		TO : "To",
		SELECT_DATE : "Select Date",
		SAVE : "Save",
		GRADE : "Grade",
		INSTUTUION_NAME : "Instution Name",
		BOARD_UNIVERSITY : "Board/University",
		APPLY : "APPLY",
		MY_COMMUNITIES : "My Communities",
		AVAILABLE_FILTERS : "Available filters",
		DISMISS : "DISMISS",
		NO_FILTERS_SELECTED : "No filter selected",
		ACCOMPLISHMENTS : "Accomplishments",
		ADD : "Add",
		PERSONAL_DETAILS : "Personal Details",
		AFFILIATIONS : "Affiliations",
		SHOW_LESS : "Show Less",
		SHOW_MORE : "Show More",
		CREATOR_OF : "Creator of",
		USERNAME : "Username",
		YOUR_PROFILE_IS : "Your profile is ",
		FOLLOW : "Follow",
		PEOPLE_YOU_FOLLOW : "People you follow",
		GROUPS_YOU_FOLLOW : "Groups you follow",
		PEOPLE_WHO_FOLLOW_YOU : "People who follow you",
		SKILL_TAGS : "Skill Tags",
		ENDORSE : "Endorse",
		MODULE_NAME : "Module Name",
		NIL : "Nil",
		PINNED_BY_ADMIN : "Pinned by Admin",
		READ_MORE : "Read more",
		THIS_IS_A_RESTRICTED_COMMUNITY : "This is a restricted community",
		DOWNLOAD_CONFIRMATION_TEXT : "Do you want to download?",
		YES : "YES",
		NO : "NO",
		ABOUT_MODULE : "ABOUT THIS MODULE",
		COMMING_SOON : "Coming Soon",
		TITLE_EDUCATION : "Education",
		TITLE_EXPERIENCES : "Experiences",
		TITLE_ADDRESS : "Address",
		LAST_NAME : "LAST NAME",
		LAST_NAME_HINT : "Enter your last name",
		NAME : "NAME",
		NAME_HINT : "Enter your name",
		GENDER : "GENDER",
		DATE_OF_BIRTH : "DATE OF BIRTH",
		CURRENT_LOCATION : "CURRENT LOCATION",
		HINT_CURRENT_LOCATION : "Enter your location",
		MODULES : "MODULES",
		BTN_CLICK_TO_OPEN_CONTENT : "Click to open content",
		NO_CHANGE : "No changes have been made",
		START_COURSE : "START COURSE",
		ERROR_INVALID_AADHAAR : "Please check the aadhaar number format",
		ERROR_CANT_SHARE_TRY_AGAIN : "Can’t share, Try again",
		ERROR_BATCH_NOT_STARTED : "Batch not started",
		MSG_NO_NEW_NOTIFICATION : "No new notification",
		MSG_NO_DETAILS_TO_SHOW : "No details to show",
		MSG_IMPORTED_SUCCESSFULLY : "Imported Successfully",
		ERROR_CANT_OPEN_EMPTY_CONTENT : "Can't open empty content",
		ERROR_NO_BATCHES_FOUND : "No batches found",
		ANSWER : "Answer",
		BTN_SUBMIT : "Submit",
		TOPIC_YOU_MIGHT_LIKE : "Topic you might like",
		OPEN_SETTINGS : "OPEN SETTINGS",
		PERMISSION_NOT_AVAILABLE : "PERMISSION NOT AVAILABLE",
		LABEL_ADD_A_SKILL : "Add a skill",
		TYPE_TO_ADD_A_SKILL : "Type to add a skill",
		ERROR_ALREADY_ADDED : "Already Added",
		WARNING_PLEASE_ADD_MANDATORY_DETAILS : "Please add mandatory details",
		WARNING_PLEASE_MAKE_SOME_CHANGES : "Please make some change",
		WARNING_INVALID_YEAR_OF_PASSING : "Invalid year of passing",
		WARNING_INVALID_PERCENTAGE : "Invalid percentage",
		WARNING_INVALID_GRADE : "Invalid grade",
		DEGREE : "Degree",
		INSTITUTION_NAME : "Institution name",
		IS_THIS_YOUR_CURRENT_JOB : "Is this your current job",
		ERROR_MULTIPLE_CURRENT_JOB : "You already have a current job, please change that to not a current job",
		OPTION_INAPPROPRIATE_CONTENT : "Inappropriate content",
		OPTION_COPYRIGHT_VIOLATION : "Copyright violation",
		OPTION_PRIVACY_VIOLATION : "Privacy violation",
		OPTION_OTHER : "Other",
		MODULE_NAME : "Module name",
		CURRENT_LOCATION : "Current location",
		HOBBIES : "Hobbies",
		EDIT_PROFILE : "Edit profile",
		ACTIVE : "Active",
		STORAGE : "Storage",
		PERMISSION_DENIED : "Permission denied",
		YEAR_OF_PASSING : "Year of passing",
		SELECT_ADDRESS_TYPE : "Select Address Type",
		LANGUAGES : "Languages",
		EMAIL : "Email",
		CHANGE_LANGUAGE : "Change language",
		/////
		ERROR_NO_RESUME_CONTENT_AVAILABLE : "Error no resume content available",
		CANCEL : "CANCEL",
		SELECT_LANGUAGE : "Select Language",
		READ_LESS : "Read Less",
		CONFIRM_DEL : "Confirm Delete?",
		ADDRESS_LINE1 : "Address Line 1",
		ADDRESS_LINE2 : "Address Line 2",
		CITY : "City",
		STATE : "State",
		COUNTRY : "Country",
		PINCODE : "Pincode",
		PERMANENT : "Permanent",
		CURRENT : "Current",
		JOB_NAME : "Job Name",
		ORGANIZATION : "Organization",
		POSITION : "Position",
		CHOOSE_FROM_FOLLOWING : "Choose from following",
		PERMISSION_SETTING_MSG : "To provide permissions, click on 'Open Settings' and provide suitable permissions.",
		DOWNLOADING: "DOWNLOADING %s %",
		ERROR_OFFLINE_MODE : "No internet, Offline mode",
		ADDITIONAL_INFORMATION : "Additional Information"
	},
	"hi_IN" : {
		ALREADY_HAVE_ACC : "मौजूदा उपयोगकर्ता, साइन इन करें",
		APPLY_FILTER : "फिल्टर लागू करें",
		AS_FILE : "फ़ाइल के रूप में साझा करें",
		AS_LINK : "लिंक के रूप में साझा करें",
		BACK_TO_EXIT : "ऐप से बाहर निकलने के लिए फिर से स्पर्श करें",
		CANCEL_DOWNLOAD : "डाउनलोड रद्द करें",
		COMING_SOON : "जल्द आ रहा है...",
		COMMUNITIES : "समुदायों",
		CONFIRM : "पुष्टि करें",
		COURSE : "कोर्स ",
		COURSE_ENROLLED : "कोर्स नामांकित",
		COURSE_PROGRESS_COMPLETED : "पूर्ण: %s",
		CONTENT_FLAGGED_MSG : "पाठ्यक्रम सफलतापूर्वक फ़्लैग किया गया",
		CONTENT_FLAG_FAIL : "पाठ्यक्रम फ़्लैगिंग विफल रहा",
		COURSES_BNAV : "कोर्स ",
		COURSES_IN_PROGRESS : " कोर्स प्रगति पर है",
		COURSES_LW : "कोर्स ",
		CREATED_BY : "के द्वारा बनाई गई",
		DELETE : "रद्द",
		DESCRIPTION : "विवरण",
		DOWNLOAD : "डाउनलोड ",
		DOWNLOADS : "डाउनलोड ",
		EDIT : "संपादित करें",
		EMAIL_ID : "ईमेल आईडी",
		EMPTY_SEARCH_RESULTS : "कोई खोज परिणाम नहीं मिला",
		ENROLL_COURSE : " कोर्स में नामांकित कराएं",
		ERROR_CONTENT_NOT_AVAILABLE : "पाठ्यक्रम अनुपलब्ध",
		ERROR_CONTENT_NOT_FOUND : "पाठ्यक्रम अभी तक उपलब्ध नहीं है",
		ERROR_DURATION_NOT_AVAILABLE : "अवधि अनुपलब्ध",
		ERROR_EMAIL_FORMAT : "गलत ईमेल प्रारूप",
		ERROR_EMPTY_EMAIL : "ईमेल आईडी दर्ज करें",
		ERROR_EMPTY_FIRSTNAME : "प्रथम नाम दर्ज करें",
		ERROR_EMPTY_LANGUAGE : "कम से कम एक भाषा चुनें",
		ERROR_EMPTY_MOBILE : "मोबाइल नंबर दर्ज करें",
		ERROR_EMPTY_PASSWORD : "पास वर्ड दर्ज करें",
		ERROR_EMPTY_USERNAME : "उपयोगकर्ता नाम दर्ज करें",
		ERROR_FETCHING_DATA : "डेटा लाने में त्रुटि",
		ERROR_NO_COURSES_ENROLLED : "कोर्स में दाखिला नहीं हुआ",
		ERROR_OFFLINE_MODE : "इंटरनेट की सुविधा नहीं है",
		ERROR_NO_OFFLINE_RESOURCE : "कोई संसाधन संग्रहीत नहीं",
		ERROR_SERVER_CONNECTION : "सर्वर से संपर्क करने में असमर्थ",
		ERROR_SERVER_MESSAGE : " त्रुटि:",
		ERROR_SHORT_MOBILE : "मोबाइल नंबर 10 अंक होना चाहिए",
		ERROR_SHORT_PASSWORD : "पासवर्ड 8 वर्णों से कम नहीं हो सकता",
		FETCHING_CONTENTS : "पाठ्यक्रम प्राप्ति:%",
		FILE_SIZE : "आकार [%s]",
		FILTER : "फिल्टर",
		FILTER_BY : "के द्वारा फिल्टर",
		FIRST_NAME : "नाम",
		FIRST_NAME_HINT : "अपना नाम दर्ज करें",
		GROUPS : "समूहों",
		GROUPS_BNAV : "समूहों",
		HINT_EMAIL_ID : "नमूने का परीक्षण",
		HINT_LANGUAGE : "पसंदीदा भाषा चुनें",
		HINT_MOBILE_NUMBER : "मोबाइल नंबर दर्ज करें",
		HINT_PASSWORD : "पासवर्ड 8 वर्णों से कम नहीं हो सकता",
		HINT_USER_NAME : "उपयोगकर्ता नाम दर्ज करें",
		HOME_BNAV : "होम",
		JOIN : "शामिल",
		LATEST_COURSES : "नवीनतम पाठ्यक्रम",
		LOADING_CONTENT : "पाठ्यक्रम लोड करें",
		LOGGED_OUT : "लॉग आउट",
		MOBILE_NUMBER : "मोबाइल नंबर",
		MODULE_SIZE : "मॉड्यूल आकार: %s",
		MODULE_SIZE_UNAVAILABLE : "मॉड्यूल का आकार अनुपलब्ध है",
		NEW : "नया",
		NO_ACC_YET : "नया उपयोगकर्ता? अब साइन अप करें",
		NO_PREVIEW : "कोई प्रीव्यू उपलब्ध नहीं  है",
		NUMBER_OF_VOTES : "वोटों की संख्या",
		OPEN : "खुला",
		PASSWORD : "पासवर्ड",
		PHONE : "फ़ोन",
		PLAY : "प्ले",
		POPULAR_COURSES : "लोकप्रिय कोर्स",
		PREVIEWS : "प्रीव्यू",
		PROFILE_BNAV : "प्रोफ़ाइल",
		PROFILE_DETAILS_TITLE : "प्रोफ़ाइल विवरण",
		PROFILE_LW : "प्रोफ़ाइल",
		PUBLISHED_DATE : "प्रकाशन की तारीख",
		QUIZ : "प्रश्नोत्तरी",
		RESOURCES_BNAV : "रिसोर्सेज ",
		RESOURCES_LW : "रिसोर्सेज",
		RESUME : "पुनः आरंभ करें",
		RETRY_ACTION : "पुनः प्रयास करें",
		SAVED_ON : "सेव्ड",
		SAVED_RESOURCES : "सहेजे गए संसाधन",
		SEARCH_HINT : "खोज",
		SELECT : "चयनित",
		SELECT_A_REASON : "कोई कारण चुनें",
		SERVER_CONNECTION_ERROR : "सर्वर से संपर्क करने में असमर्थ",
		SHARE_THIS : "शेयर",
		SIGN_IN : "साइन इन करें",
		SIGN_UP : "साइन अप करें",
		SORT_BY : "आधार पर छाँटे",
		SPLASH_MESSAGE : "एनसीटीई",
		STRUCTURE : "संरचना",
		TO_DO : " टो डो",
		USER_NAME : "उपयोगकर्ता नाम",
		VIEW_ALL : "सभी को देखें",
		VIEW_ALL_COMMUNITIES : "सभी शामिल हुए समुदायों को देखें",
		VIEW_MORE : "अधिक...",
		WAIT_REQUEST : "कृपया प्रतीक्षा करें",
		WELCOME_BACK : "फिर से स्वागत, %s",
		WELCOME_M1 : "एनटीपी में आपका स्वागत है",
		WELCOME_M2 : "शिक्षकों के लिए ढांचे की संरचना",
		WELCOME_ON_BOARD : "एनटीपी में आपका स्वागत है",
		WHAT_WENT_WRONG : "क्या गलत हुआ",
		YOUR_PROGRESS : "आपकी प्रगति प्रतिशत",
		FLAG : "रिपोर्ट",
		ERROR_EMPTY_RESULT : "खोज परिणाम अनुपलब्ध",
		ERROR_FLAG_CONTENT_MIN_REASON : " पाठ्यक्रम फ्लैग करने के लिए कम से कम एक कारण चुनें",
		ERROR_INVALID_EMAIL : "अमान्य ईमेल आईडी",
		MSG_RESOURCE_DELETED : "डिवाइस से सामग्री हटाई गई",
		LOGOUT : "साइन आउट",
		CREATOR_NAME_NOT_AVAILABLE : "निर्माता का नाम अनुपलब्ध है",
		ENROLL : "नामांकन",
		VIEW_ONGOING_BATCHES : "चल रहे बैचों को देखें",
		VIEW_UPCOMING_BATCHES : "आगामी बैचों देखें",
		USER_NAME_PROFILE : "उपयोगकर्ता नाम",
		BATCHES_FOR_THIS_COURSE : "इस पाठ्यक्रम के लिए बैचों",
		ERROR_EMPTY_FIELDS : "विवरण दर्ज करें",
		INVALID_CONTENT : "सामग्री अमान्य है",
		TIME_OUT : "सर्वर का समय समाप्त हुआ बाद में पुन: प्रयास करें",
		OPTIONAL : "ऐच्छिक",
		PERCENTAGE : "प्रतिशत",
		SUBJECTS : "विषयों",
		FROM : "से",
		TO : "यहाँ",
		SELECT_DATE : "तारीख़ चुनें",
		SAVE : "सेव्ड",
		GRADE : "ग्रेड",
		INSTUTUION_NAME : "संस्था का नाम",
		BOARD_UNIVERSITY : "बोर्ड / विश्वविद्यालय",
		APPLY : "लागू करें",
		MY_COMMUNITIES : "मेरे समुदाय",
		AVAILABLE_FILTERS : "फ़िल्टर लागू करें",
		DISMISS : "रद्द",
		NO_FILTERS_SELECTED : "कोई फ़िल्टर चयनित नहीं है",
		ACCOMPLISHMENTS : "उपलब्धियों",
		ADD : "जोड़",
		PERSONAL_DETAILS : "व्यक्तिगत विवरण",
		AFFILIATIONS : "जुड़ाव",
		SHOW_LESS : "कम दिखाएं",
		SHOW_MORE : "और दिखाएं",
		CREATOR_OF : "के द्वारा बनाई गई",
		USERNAME : "उपयोगकर्ता नाम: %s",
		YOUR_PROFILE_IS : "आपकी प्रोफ़ाइल %s पूर्ण है",
		FOLLOW : "का पालन करें",
		PEOPLE_YOU_FOLLOW : "लॉग जिनका आप अनुसरण करते हो",
		GROUPS_YOU_FOLLOW : "जिन समूहों का आप अनुसरण करते हैं",
		PEOPLE_WHO_FOLLOW_YOU : "जो लोग आपका अनुसरण करते हैं",
		SKILL_TAGS : "कौशल टैग",
		ENDORSE : "संलग्न",
		MODULE_NAME : "मोड्यूल का नाम",
		NIL : "शून्य",
		PINNED_BY_ADMIN : "व्यवस्थापक द्वारा पिन किया गया",
		READ_MORE : "आगे पढ़े",
		THIS_IS_A_RESTRICTED_COMMUNITY : "यह एक सीमित समुदाय है",
		DOWNLOAD_CONFIRMATION_TEXT : "क्या आप डाउनलोड करना चाहते हैं?",
		YES : "हाँ",
		NO : "नहीं",
		COMMING_SOON : "जल्द आ रहा है...",
		TITLE_EDUCATION : "शिक्षा",
		TITLE_EXPERIENCES : "अनुभव",
		TITLE_ADDRESS : "पता",
		LAST_NAME : "उपनाम",
		LAST_NAME_HINT : "अपना उपनाम दर्ज करें",
		NAME : "नाम",
		NAME_HINT : "अपना नाम दर्ज करें",
		GENDER : "लिंग",
		DATE_OF_BIRTH : "जन्म तारीख",
		CURRENT_LOCATION : "वर्तमान स्थान",
		HINT_CURRENT_LOCATION : "अपनी स्थिति दर्ज़ करें",
		MODULES : "मॉड्यूल",
		BTN_CLICK_TO_OPEN_CONTENT : "सामग्री को खोलने के लिए क्लिक करें",
		NO_CHANGE : "कोई बदलाव नहीं किया गया है",
		START_COURSE : "स्टार्ट कोर्स",
		ERROR_INVALID_AADHAAR : "कृपया आधार संख्या प्रारूप की जांच करें",
		ERROR_CANT_SHARE_TRY_AGAIN : "साझा नहीं कर सकते, पुनः प्रयास करें",
		ERROR_BATCH_NOT_STARTED : "बैच शुरू नहीं हुआ",
		MSG_NO_NEW_NOTIFICATION : "कोई नई सूचना नहीं",
		MSG_NO_DETAILS_TO_SHOW : "दिखाने के लिए कोई विवरण नहीं",
		MSG_IMPORTED_SUCCESSFULLY : "सफलतापूर्वक आयात किया गया",
		ERROR_CANT_OPEN_EMPTY_CONTENT : "खाली सामग्री नहीं खोल सकता",
		ERROR_NO_BATCHES_FOUND : "कोई बैच नहीं मिला",
		ANSWER : "उत्तर",
		BTN_SUBMIT : "जमा करें",
		TOPIC_YOU_MIGHT_LIKE : "विषय आपको पसंद हो सकता है",
		OPEN_SETTINGS : "सेटिंग्स खोलें",
		PERMISSION_NOT_AVAILABLE : "अनुमति उपलब्ध नहीं है",
		LABEL_ADD_A_SKILL : "एक कौशल जोड़ें",
		TYPE_TO_ADD_A_SKILL : "एक कौशल जोड़ने के लिए टाइप करें",
		ERROR_ALREADY_ADDED : "पहले से ही जोड़ा",
		WARNING_PLEASE_ADD_MANDATORY_DETAILS : "कृपया अनिवार्य विवरण जोड़ें",
		WARNING_PLEASE_MAKE_SOME_CHANGES : "कृपया कुछ बदलाव करें",
		WARNING_INVALID_YEAR_OF_PASSING : "पारित होने का अमान्य वर्ष",
		WARNING_INVALID_PERCENTAGE : "अमान्य प्रतिशत",
		WARNING_INVALID_GRADE : "अमान्य ग्रेड",
		DEGREE : "हद",
		INSTITUTION_NAME : "निर्देश नाम",
		IS_THIS_YOUR_CURRENT_JOB : "क्या यह आपकी वर्तमान नौकरी है",
		ERROR_MULTIPLE_CURRENT_JOB : "आपके पास पहले से एक मौजूदा नौकरी है, कृपया इसे चालू नौकरी न करें",
		OPTION_INAPPROPRIATE_CONTENT : "अनुचित सामग्री",
		OPTION_COPYRIGHT_VIOLATION : "कॉपीराइट उल्लंघन",
		OPTION_PRIVACY_VIOLATION : "गोपनीयता उल्लंघन",
		OPTION_OTHER : "अन्य",
		MODULE_NAME : "मोड्यूल का नाम",
		CURRENT_LOCATION : "वर्तमान स्थान",
		HOBBIES : "शौक",
		EDIT_PROFILE : "प्रोफाइल एडिट करें",
		ACTIVE : "सक्रिय",
		STORAGE : "संग्रहण",
		PERMISSION_DENIED : "अनुमति नहीं मिली",
		YEAR_OF_PASSING : "उत्तीर्ण होने का वर्ष",
		SELECT_ADDRESS_TYPE : "पता प्रकार चुनें",
		LANGUAGES : "भाषाएं",
		EMAIL : "ईमेल",
		CHANGE_LANGUAGE : "भाषा बदलो",
		/////
		ERROR_NO_RESUME_CONTENT_AVAILABLE : "कोई सामग्री फिर से शुरू उपलब्ध नहीं है",
		CANCEL : "रद्द करें",
		SELECT_LANGUAGE : "भाषा चुनिए",
		READ_LESS : "कम पढ़ें",
		CONFIRM_DEL : "हटाने की पुष्टि करें?",
		ADDRESS_LINE1 : "पता पंक्ति 1",
		ADDRESS_LINE2 : "पता पंक्ति 2",
		CITY : "शहर",
		STATE : "राज्य",
		COUNTRY : "देश",
		PINCODE : "पिन कोड",
		PERMANENT : "स्थायी",
		CURRENT : "चालू",
		JOB_NAME : "कार्य नाम",
		ORGANIZATION : "संगठन",
		POSITION : "पद",
		CHOOSE_FROM_FOLLOWING : "निम्नलिखित से चुनें"
	},
	"ta_IN" : {
		ALREADY_HAVE_ACC : "முன்னரே அக்கௌன்ட் இருக்கிறதா? சைன் இன் செய்யுங்கள்.",
		APPLY_FILTER : "பில்ட்டர் செய்க",
		AS_FILE : "கோப்பு வடிவத்தில் ",
		AS_LINK : "லின்க் வடிவத்தில்",
		BACK_TO_EXIT : "குறுஞ்செயிலி விட்டு வெளியேற பேக் பட்டனை மற்றொன்று முறை அழுத்தவும்.",
		CANCEL_DOWNLOAD : "டவுன்லோடை ரத்துசெய்",
		COMING_SOON : "விரைவில் வரும்.........",
		COMMUNITIES : "சமூகங்கள்",
		CONFIRM : "உறுதிசெய்யுங்கள்",
		COURSE : "கோர்ஸ்",
		COURSE_ENROLLED : "கோர்ஸ் பதிவு செய்யப்பட்டது",
		COURSE_PROGRESS_COMPLETED : "%s % முடிந்தது",
		CONTENT_FLAGGED_MSG : "வெற்றிகரமாகப் பாடம் பிளாக் செய்யப்பட்டது",
		CONTENT_FLAG_FAIL : "பாடத்தை பிளாக் செய்வது தோல்வியடைந்தது",
		COURSES_BNAV : "கோர்ஸ்கள்",
		COURSES_IN_PROGRESS : "கோர்ஸ்கள் மேம்படுகிறது",
		COURSES_LW : "கோர்ஸ்கள்",
		CREATED_BY : "உருவாக்கியவர்",
		DELETE : "அகற்று",
		DESCRIPTION : "விவரங்கள்",
		DOWNLOAD : "டவுன்லோட்",
		DOWNLOADS : "டவுன்லோடுகள்",
		EDIT : "திருத்து",
		EMAIL_ID : "மின்னஞ்சல் ஐடி",
		EMPTY_SEARCH_RESULTS : "உங்கள் தேடலுக்குறிய முடிவுகள் இல்லை",
		ENROLL_COURSE : "இந்த கோர்ஸை பதிவு செய்யுங்கள்",
		ERROR_CONTENT_NOT_AVAILABLE : "பாடம் கிடைக்கவில்லை",
		ERROR_CONTENT_NOT_FOUND : "பாடங்கள் இன்னும் சேர்க்கவில்லை",
		ERROR_DURATION_NOT_AVAILABLE : "கால நேரம் கிடைக்கவில்லை",
		ERROR_EMAIL_FORMAT : "தவறான மின்னஞ்சல் வடிவம் ",
		ERROR_EMPTY_EMAIL : "தங்கள் மின்னஞ்சல் ஐடி யை பதியுங்கள்",
		ERROR_EMPTY_FIRSTNAME : "தங்கள் பெயரை பதியுங்கள்",
		ERROR_EMPTY_LANGUAGE : "குறைந்தது ஒரு மொழியாவது தேர்வுசெயுங்கள்",
		ERROR_EMPTY_MOBILE : "தங்கள் கைபேசி எண்ணை பதியுங்கள்",
		ERROR_EMPTY_PASSWORD : "தங்கள் கடவுச்சொல்லை பதியுங்கள்",
		ERROR_EMPTY_USERNAME : "பயனர் பெயரை பதியுங்கள்",
		ERROR_FETCHING_DATA : "டேட்டா பெறுவதில் பிழை ஏற்பட்டுள்ளது",
		ERROR_NO_COURSES_ENROLLED : "எந்த கோர்ஸும் இன்னும் பதிவு செய்யப்படவில்லை",
		ERROR_OFFLINE_MODE : "தங்கள் கைப்பேசி இணையத்திடம் இணைக்கப்படவில்லை.",
		ERROR_NO_OFFLINE_RESOURCE : "இன்னும்  ஆஃப்லைன் ரிசோர்ஸ எதுவும் இல்லை",
		ERROR_SERVER_CONNECTION : "சேவையகத்துடன் தொடர்புகொள்ள முடியவில்லை",
		ERROR_SERVER_MESSAGE : "பிழை",
		ERROR_SHORT_MOBILE : "தொலைப்பேசி எண் வடிவத்தைப் பரிசோதிக்கவும்",
		ERROR_SHORT_PASSWORD : "கடவுச்சொல்லை எட்டு எழுத்துக்களுக்குக் குறைவாக இருக்கமுடியாது",
		FETCHING_CONTENTS : "பாடங்கள் பெறுகிறது: %s %",
		FILE_SIZE : "அளவு [%s]",
		FILTER : "பில்டர்",
		FILTER_BY : "இதன் அடிப்படையில் பில்டர் செய்க",
		FIRST_NAME : "பெயர்",
		FIRST_NAME_HINT : "தங்கள் பெயரை பதிவுசெய்யுங்கள்",
		GROUPS : "குழுக்கள்",
		GROUPS_BNAV : "குழுக்கள்",
		HINT_EMAIL_ID : "sample@test.com",
		HINT_LANGUAGE : "தங்களுக்கு அனுகூலமான மொழியைத் தேர்வு செய்துகொள்ளுங்கள்",
		HINT_MOBILE_NUMBER : "தங்கள் தொலைப்பேசி எண்ணைப் பதிவு செயுங்கள்",
		HINT_PASSWORD : "கடவுச்சொல் குறைந்தது எட்டு எழுத்துக்கல் இருக்கவேண்டும்.",
		HINT_USER_NAME : "பயனர் பெயரை பதியுங்கள்",
		HOME_BNAV : "ஹோம்",
		JOIN : "சேறுங்கள்",
		LATEST_COURSES : "புதிய கோர்ஸ்கள்",
		LOADING_CONTENT : "பாடம் லோடாகிறது",
		LOGGED_OUT : "வெளியேற்றப்பட்டீர்கள்",
		MOBILE_NUMBER : "தொலைப்பேசி எண்",
		MODULE_SIZE : "மாடியுள் அளவு: %s",
		MODULE_SIZE_UNAVAILABLE : "மாடியுள் அளவு கிடைக்கவில்லை",
		NEW : "புதியது",
		NO_ACC_YET : "புது பயனரா? இப்போது பதிவு செய்க",
		NO_PREVIEW : "முன்னோட்ட தற்சமயம் காணமுடியாது",
		NUMBER_OF_VOTES : "மொத்த வாக்குகள்",
		OPEN : "திறன்டிடுங்கள்",
		PASSWORD : "கடவுச்சொல்லை",
		PHONE : "தொலைப்பேசி",
		PLAY : "பிளே",
		POPULAR_COURSES : "பிரபலமான கோர்ஸ்கள்",
		PREVIEWS : "முன்னோட்டங்கள்",
		PROFILE_BNAV : "ப்ரொபைல்",
		PROFILE_DETAILS_TITLE : "ப்ரொபைல் விவரங்கள்",
		PROFILE_LW : "ப்ரொபைல்",
		PUBLISHED_DATE : "வெளியிடப்பட்ட தேதி",
		QUIZ : "வினாடி வினா",
		RESOURCES_BNAV : "ரிசோர்ஸ்கள்",
		RESOURCES_LW : "ரிசோர்ஸ்கள்",
		RESUME : "விட்ட இடத்தில் இருந்து தொடருக",
		RETRY_ACTION : "மீண்டும் முயற்ச்சிக்கவும்",
		SAVED_ON : "சேமித்தவை",
		SAVED_RESOURCES : "சேமித்த ரிசோர்ஸ்கள்",
		SEARCH_HINT : "தேடு",
		SELECT : "தேர்வு செய்யுங்கள்",
		SELECT_A_REASON : "காரணத்தை தேர்வு செய்யுங்கள்",
		SERVER_CONNECTION_ERROR : "சேவையகத்துடன் தொடர்புகொள்ள முடியவில்லை",
		SHARE_THIS : "பகிருங்கள்",
		SIGN_IN : "சைன் இன்",
		SIGN_UP : "சைன் அப்",
		SORT_BY : "மூலம் வரிசைப்படுட்டுங்கள்",
		SPLASH_MESSAGE : "என்.சி.டி.சி திட்டம்",
		STRUCTURE : "அமைப்பு",
		TO_DO : "செய்ய வேண்டியவை",
		USER_NAME : "பயனர் பெயர்",
		VIEW_ALL : "அனைத்தையும் காட்டு",
		VIEW_ALL_COMMUNITIES : "தாங்கள் அங்கமாக இருக்கும் அனைத்து சமூகங்களையும் காட்டு",
		VIEW_MORE : "மேலும் காட்டு",
		WAIT_REQUEST : "தயவுசெய்து காத்திருக்கவும்",
		WELCOME_BACK : "மீண்டும் வருக %s",
		WELCOME_M1 : "என்.டி.பிக்கு வரவேற்கிறோம்",
		WELCOME_M2 : "கல்வியாளர்களுக்கான கட்டமைக்கப்பட்ட கல்வி",
		WELCOME_ON_BOARD : "என்.டி.பிக்கு வரவேற்கிறோம், %s",
		WHAT_WENT_WRONG : "என்ன தவறு நடந்தது?",
		YOUR_PROGRESS : "தங்கள் முன்னேற்றம்: %s%",
		FLAG : "குறி",
		ERROR_EMPTY_RESULT : "எந்த முடிவுகளும் தற்போது இல்லை",
		ERROR_FLAG_CONTENT_MIN_REASON : "தயவுசெய்து பாடத்தை குறித்ததுக்காக குறைந்தது ஒரு காரணத்தை தேர்வு செய்யுங்கள்",
		ERROR_INVALID_EMAIL : "தவறான மின்னஞ்சல் ஐடி",
		MSG_RESOURCE_DELETED : "தங்கள் சாதனத்தில் இருந்து   பாடம் அழிக்க பட்டது",
		LOGOUT : "லாக் அவுட்",
		CREATOR_NAME_NOT_AVAILABLE : "உருவாக்கியவர் பெயர் கிடைக்கவில்லை",
		ENROLL : "பதிவு செய்யுங்கள்",
		VIEW_ONGOING_BATCHES : "நடப்பு பச்சஸ்கலை பாருங்கள்",
		VIEW_UPCOMING_BATCHES : "வரப்போகும் பச்சஸ்கலை பாருங்கள்",
		USER_NAME_PROFILE : "பயனர் பெயர்",
		BATCHES_FOR_THIS_COURSE : "இந்த கோர்ஸுக்காண பச்சஸ்",
		ERROR_EMPTY_FIELDS : "விவரங்களை பதிவுசெய்யுங்கள்",
		INVALID_CONTENT : "தவறான பாடம்",
		TIME_OUT : "சேவையக நேரம் முடிந்தது, பிறகு மீண்டும் முயற்சிக்கவும்",
		OPTIONAL : "கட்டாயம் அற்றவை",
		PERCENTAGE : "சதவீதம்",
		SUBJECTS : "பாடங்கள்",
		FROM : "இருந்து",
		TO : "அங்கே",
		SELECT_DATE : "தேதி தேர்வுசெய்யுங்கள்",
		SAVE : "செவ் செய்யுங்கள்",
		GRADE : "வகுப்பு",
		INSTUTUION_NAME : "இயக்க பெயர்",
		BOARD_UNIVERSITY : "வாரியம் / பல்கலைக்கழகம்",
		APPLY : "பில்ட்டர் செய்யுங்கள்",
		MY_COMMUNITIES : "என் சமுதாயங்கள்",
		AVAILABLE_FILTERS : "பில்ட்டர்கள்",
		DISMISS : "ரத்து செய்யுங்கள்",
		NO_FILTERS_SELECTED : "எந்த பில்டரும் ஆய்வு செய்யவில்லை",
		ACCOMPLISHMENTS : "சாதனைகள்/சிறப்புத் தகுதிகள்",
		ADD : "சேறு",
		PERSONAL_DETAILS : "சொந்த விவரங்கள்",
		AFFILIATIONS : "தொடர்புகள்",
		SHOW_LESS : "குறைபாக காட்டவும்",
		SHOW_MORE : "இன்னும் நிறைய காட்டவும்",
		CREATOR_OF : "உருவாக்கியவர்",
		USERNAME : "பயனர் பெயர்",
		YOUR_PROFILE_IS : "தங்கள் ப்ரொபைல் %s முடிந்தது",
		FOLLOW : "பின்பற்று",
		PEOPLE_YOU_FOLLOW : "நீங்கள் பின்பற்றும் நபர்கள்",
		GROUPS_YOU_FOLLOW : "நீங்கள் பின்பற்றும் குழுக்கள்",
		PEOPLE_WHO_FOLLOW_YOU : "உங்களை பின்பற்றும் நபர்கள்",
		SKILL_TAGS : "திறன் குறிச்சொற்கள்",
		ENDORSE : "ஆதரியுங்கள்",
		MODULE_NAME : "மாடியுளின் பெயர்",
		NIL : "எதுவும் இல்லை",
		PINNED_BY_ADMIN : "நிர்வாகிப்பவரால் பின் செய்யப்பட்டுள்ளது",
		READ_MORE : "அதிகம் படிக்க",
		THIS_IS_A_RESTRICTED_COMMUNITY : "இது ஒரு வரையறைப்படுத்திய சமுகம்",
		DOWNLOAD_CONFIRMATION_TEXT : "தங்கள் இதை டவுன்லோட் செய்ய விரும்புகிறீர்களா?",
		YES : "ஆம்",
		NO : "இல்லை",
		ABOUT_MODULE : "இந்த மாடியுளை பற்றி அறிய",
		COMMING_SOON : "விரைவில் வருகிறேன்",
		TITLE_EDUCATION : "கல்வி",
		TITLE_EXPERIENCES : "அனுபவங்கள்",
		TITLE_ADDRESS : "முகவரி",
		LAST_NAME : "குடும்ப",
		LAST_NAME_HINT : "உங்கள் கடைசி பெயரை உள்ளிடவும்",
		NAME : "பெயர்",
		NAME_HINT : "உங்கள் பெயரை உள்ளிடவும்",
		GENDER : "பாலினம்",
		DATE_OF_BIRTH : "பிறந்த தேதி",
		CURRENT_LOCATION : "உங்கள் இருப்பிடத்தை உள்ளிடவும்",
		HINT_CURRENT_LOCATION : "உங்கள் இருப்பிடத்தை உள்ளிடவும் ",
		MODULES : "தொகுதிகள்",
		BTN_CLICK_TO_OPEN_CONTENT : "உள்ளடக்கத்தைத் திறக்க கிளிக் செய்க",
		NO_CHANGE : "மாற்றங்கள் செய்யப்படவில்லை",
		START_COURSE : "தொடக்க பாடத்திட்டம்",
		ERROR_INVALID_AADHAAR : "தயவுசெய்து அத்தாஹார் எண் வடிவத்தை சரிபார்க்கவும்",
		ERROR_CANT_SHARE_TRY_AGAIN : "பகிர முடியாது, மீண்டும் முயற்சிக்கவும்",
		ERROR_BATCH_NOT_STARTED : "பேட்ச் தொடங்கவில்லை",
		MSG_NO_NEW_NOTIFICATION : "புதிய அறிவிப்பு இல்லை",
		MSG_NO_DETAILS_TO_SHOW : "காட்ட எந்த விவரமும் இல்லை",
		MSG_IMPORTED_SUCCESSFULLY : "வெற்றிகரமாக இறக்குமதி செய்யப்பட்டது",
		ERROR_CANT_OPEN_EMPTY_CONTENT : "வெற்று உள்ளடக்கத்தை திறக்க முடியவில்லை",
		ERROR_NO_BATCHES_FOUND : "எந்த தொகுப்புகளும் கண்டுபிடிக்கப்படவில்லை",
		ANSWER : "பதில்",
		BTN_SUBMIT : "சமர்ப்பி",
		TOPIC_YOU_MIGHT_LIKE : "நீங்கள் விரும்பக்கூடிய தலைப்பு",
		OPEN_SETTINGS : "திறக்க அமைப்புகள்",
		PERMISSION_NOT_AVAILABLE : "அனுமதி இல்லை அனுமதி",
		LABEL_ADD_A_SKILL : "ஒரு திறமையைச் சேர்க்கவும்",
		TYPE_TO_ADD_A_SKILL : "திறமை சேர்க்க வகை செய்க",
		ERROR_ALREADY_ADDED : "ஏற்கனவே சேர்க்கப்பட்டது",
		WARNING_PLEASE_ADD_MANDATORY_DETAILS : "கண்டிப்பாக விவரங்களைச் சேர்க்கவும்",
		WARNING_PLEASE_MAKE_SOME_CHANGES : "சில மாற்றங்களைச் செய்யுங்கள்",
		WARNING_INVALID_YEAR_OF_PASSING : "செல்லாத ஆண்டு செல்லாதது",
		WARNING_INVALID_PERCENTAGE : "தவறான சதவீதம்",
		WARNING_INVALID_GRADE : "தவறான தரம்",
		DEGREE : "பட்டம்",
		INSTITUTION_NAME : "உங்களின் பெயர்",
		IS_THIS_YOUR_CURRENT_JOB : "இது உங்கள் தற்போதைய வேலை",
		ERROR_MULTIPLE_CURRENT_JOB : "நீங்கள் ஏற்கனவே ஒரு வேலையை வைத்திருக்கிறீர்கள், தயவுசெய்து நடப்பு வேலையை செய்ய வேண்டாம் என்று மாற்றவும்",
		OPTION_INAPPROPRIATE_CONTENT : "பொருத்தமற்ற உள்ளடக்கம்",
		OPTION_COPYRIGHT_VIOLATION : "பதிப்புரிமை மீறல்",
		OPTION_PRIVACY_VIOLATION : "தனியுரிமை மீறல்",
		OPTION_OTHER : "மற்ற",
		MODULE_NAME : "தொகுதி பெயர்",
		CURRENT_LOCATION : "தற்போதைய இடம்",
		HOBBIES : "பொழுதுபோக்குகள்",
		EDIT_PROFILE : "சுயவிவரத்தைத் திருத்தவும்",
		ACTIVE : "செயலில்",
		STORAGE : "சேமிப்பு மறுக்கப்பட்டது",
		PERMISSION_DENIED : "அனுமதி மறுக்கப்பட்டது",
		YEAR_OF_PASSING : "கடந்து செல்லும் ஆண்டு",
		SELECT_ADDRESS_TYPE : "முகவரி வகை தேர்ந்தெடு",
		LANGUAGES : "மொழிகள்",
		EMAIL : "மின்னஞ்சல் ஐடி",
		CHANGE_LANGUAGE : "மொழியை மாற்று",
		/////
		ERROR_NO_RESUME_CONTENT_AVAILABLE : "உள்ளடக்கத்தை மறுதொடக்கம் செய்வதில் பிழை இல்லை",
		CANCEL : "ரத்து",
		SELECT_LANGUAGE : "மொழியைத் தேர்ந்தெடுக்கவும்",
		READ_LESS : "குறைவாகப் படிக்கவும்",
		CONFIRM_DEL : "நீக்குதலை உறுதிப்படுத்தவா?",
		ADDRESS_LINE1 : "முகவரி வரி 1",
		ADDRESS_LINE2 : "முகவரி வரி 2",
		CITY : "நகரம்்",
		STATE : "நிலைை",
		COUNTRY : "நாட்டின்",
		PINCODE : "அஞ்சல் குறியீடு",
		PERMANENT : "நிரந்தர",
		CURRENT : "தற்போதைய",
		JOB_NAME : "வேலை பெயர்",
		ORGANIZATION : "அமைப்பு",
		POSITION : "நிலை",
		CHOOSE_FROM_FOLLOWING : "தொடர்ந்து இருந்து தேர்வு"
	},
	"te_IN" : {
		ALREADY_HAVE_ACC : "అకౌంట్ ఉందా? లాగిన్ అవ్వండి",
		APPLY_FILTER : "ఫిల్టర్ చెయ్యండి",
		AS_FILE : "ఫైల్‌గా",
		AS_LINK : "లింకుగా",
		BACK_TO_EXIT : "ఆప్ బయటకు వెళ్ళడానికి మళ్ళీ నొక్కండి",
		CANCEL_DOWNLOAD : "డౌన్‌లోడ్ వద్దు",
		COMING_SOON : "త్వరలో...",
		COMMUNITIES : "కమ్యూనిటీలు",
		CONFIRM : "నిర్ధారించండి",
		COURSE : "కోర్సు",
		COURSE_ENROLLED : "కోర్సులో నమోదు అయ్యారు",
		COURSE_PROGRESS_COMPLETED : "%s % పూర్తయింది",
		CONTENT_FLAGGED_MSG : "కంటెంట్ ఫ్లాగ్ చెయ్యబడింది ",
		CONTENT_FLAG_FAIL : "కంటెంట్ ఫ్లాగ్ చెయ్యడం అవ్వలేదు",
		COURSES_BNAV : "కోర్సులు",
		COURSES_IN_PROGRESS : "జరుగుతున్న కోర్సులు",
		COURSES_LW : "కోర్సులు",
		CREATED_BY : "తయారుచేసినది",
		DELETE : "తొలగించు",
		DESCRIPTION : "వివరణ",
		DOWNLOAD : "డౌన్‌లోడ్",
		DOWNLOADS : "డౌన్‌లోడ్ సంఖ్య",
		EDIT : "మార్చు",
		EMAIL_ID : "ఈమెయిల్ ఐడీ",
		EMPTY_SEARCH_RESULTS : "వెతికినవి లేవు",
		ENROLL_COURSE : "ఈ కోర్సులో నమోదు చెయ్యి",
		ERROR_CONTENT_NOT_AVAILABLE : "కంటెంట్ అందుబాటులో లేదు",
		ERROR_CONTENT_NOT_FOUND : "కంటెంట్ దొరక లేదు",
		ERROR_DURATION_NOT_AVAILABLE : "వ్యవధి తెలియదు",
		ERROR_EMAIL_FORMAT : "ఈమెయిల్ ఫార్మేట్ తప్పుగా ఉంది ",
		ERROR_EMPTY_EMAIL : "ఈమెయిల్ ఇవ్వండి",
		ERROR_EMPTY_FIRSTNAME : "పేరు ఇవ్వండి",
		ERROR_EMPTY_LANGUAGE : "కనీసం ఒక భాషను ఎంచుకోండి",
		ERROR_EMPTY_MOBILE : "మొబైల్ నెంబరు ఇవ్వండి",
		ERROR_EMPTY_PASSWORD : "పాస్‌వర్డ్ ఇవ్వండి",
		ERROR_EMPTY_USERNAME : "వాడకందారు పేరు ఇవ్వండి",
		ERROR_FETCHING_DATA : "డాటా తెచ్చుకోడంలో ఏదో ఇబ్బంది వచ్చింది",
		ERROR_NO_COURSES_ENROLLED : "ఏ కోర్సులోనూ నమోదు కాలేదు",
		ERROR_OFFLINE_MODE : "ఇంటర్నెట్టు లేదు",
		ERROR_NO_OFFLINE_RESOURCE : "దిగుమతి అయిన రిసోర్సులు లేవు",
		ERROR_SERVER_CONNECTION : "సర్వర్‌కి కనెక్షన్ లేదు",
		ERROR_SHORT_MOBILE : "మొబైల్ నెంబర్ 10 అంకెల సంఖ్య అయ్యుండాలి",
		ERROR_SHORT_PASSWORD : "పాస్‌వర్డ్ 8 అక్షరాల కన్నా తక్కువ ఉండలేదు",
		FETCHING_CONTENTS : "కంటెంటు వస్తోంది: %s %",
		FILE_SIZE : "కంటెంటు పరిమాణం",
		FILTER : "వడపోత-ఫిల్టర్",
		FILTER_BY : "వడపోత వివరాలు",
		FIRST_NAME : "పేరు",
		FIRST_NAME_HINT : "మీ పేరు ఇవ్వండి",
		GROUPS : "గుంపులు",
		GROUPS_BNAV : "గుంపులు",
		HINT_LANGUAGE : "కావలసిన భాషని ఎన్నుకోండి",
		HINT_MOBILE_NUMBER : "మొబైల్ నెంబరు ఇవ్వండి",
		HINT_PASSWORD : "పాస్‌వర్డ్ కనీసం 8 అక్షరాల ఉండాలి",
		HINT_USER_NAME : "వాడకందారు పేరు ఇవ్వండి ",
		HOME_BNAV : "మొదటి పేజీ",
		JOIN : "చేరండి",
		LATEST_COURSES : "తాజా కోర్సులు",
		LOADING_CONTENT : "కంటెంటు లోడ్ అవుతోంది",
		LOGGED_OUT : "లాగౌట్ అయ్యారు",
		MOBILE_NUMBER : "మొబైల్ నెంబరు",
		MODULE_SIZE : "మాడ్యూల్ పరిమాణం",
		MODULE_SIZE_UNAVAILABLE : "మాడ్యూల్ పరిమాణం దొరకలేదు",
		NEW : "కొత్తది",
		NO_ACC_YET : "కొత్త వాడకందారా? లాగిన్ తయారు చేసుకోండి",
		NO_PREVIEW : "ప్రివ్యూ లేదు",
		NUMBER_OF_VOTES : "ఓట్ల సంఖ్య",
		OPEN : "తెరువండి",
		PASSWORD : "పాస్‌వర్డ్",
		PHONE : "ఫోను",
		PLAY : "ప్లే చెయ్యండి",
		POPULAR_COURSES : "జనాదరణ పొందిన కోర్సులు",
		PREVIEWS : "ప్రివ్యూలు",
		PROFILE_BNAV : "ప్రొఫైలు",
		PROFILE_DETAILS_TITLE : "ప్రొఫైల్ వివరాలు",
		PROFILE_LW : "ప్రొఫైలు",
		PUBLISHED_DATE : "ప్రచురించిన తేదీ",
		QUIZ : "క్విజ్",
		RESOURCES_BNAV : "రిసోర్సులు",
		RESOURCES_LW : "రిసోర్సులు",
		RESUME : "మళ్ళీ మొదలుపెట్టు",
		RETRY_ACTION : "మరోసారి ప్రయత్నించండి",
		SAVED_ON : "సేవ్ చేసిన తేదీ",
		SAVED_RESOURCES : "సేవ్ అయిన రిసోర్సులు",
		SEARCH_HINT : "వెతకండి",
		SELECT : "ఎన్నుకోండి",
		SELECT_A_REASON : "కారణం ఎన్నుకోండి",
		SERVER_CONNECTION_ERROR : "సర్వర్‌కి కనెక్షన్ లేదు",
		SHARE_THIS : "షేర్ చెయ్యండి",
		SIGN_IN : "లాగిన్ అవ్వండి",
		SIGN_UP : "లాగిన్ తయారుచేసుకోండి",
		SORT_BY : "క్రమంలో పెట్టండి",
		SPLASH_MESSAGE : "ఎన్.సి.టి.ఇ  ప్రాజెక్టు ",
		STRUCTURE : "నిర్మాణం",
		TO_DO : "చెయ్య వలసినవి",
		USER_NAME : "వాడకందారు పేరు",
		VIEW_ALL : "పూర్తిగా చూడండి",
		VIEW_ALL_COMMUNITIES : "మీరు నమోదైన కమ్యూనిటీలను చూడండి",
		VIEW_MORE : "మరిన్ని చూడండి",
		WAIT_REQUEST : "దయచేసి వేచి ఉండండి",
		WELCOME_BACK : "%s - మీకు తిరిగి స్వాగతం",
		WELCOME_M1 : "ఎన్‌టిపికి స్వాగతం",
		WELCOME_M2 : "అధ్యాపకులకు నిర్మాణాత్మక అధ్యాపనం",
		WELCOME_ON_BOARD : "ఎన్‌టిపికి స్వాగతం, %s",
		WHAT_WENT_WRONG : "ఏం పొరపాటు జరిగింది?",
		YOUR_PROGRESS : "మీ ప్రగతి: %s%",
		FLAG : "ఫ్లాగ్/రిపోర్టు చెయ్యండి",
		ERROR_EMPTY_RESULT : "వెతుకులాటకు ఫలితాలు లేవు",
		ERROR_FLAG_CONTENT_MIN_REASON : "కంటెంటు ఫ్లాగ్ చెయ్యడానికి కనీసం ఒక కారణాన్ని ఎన్నుకోండి.",
		ERROR_INVALID_EMAIL : "ఇమెయిల్ ఐడి సరికాదు",
		MSG_RESOURCE_DELETED : "కంటెంటు తొలగించబడింది",
		LOGOUT : "లాగౌట్",
		CREATOR_NAME_NOT_AVAILABLE : "తయారుచేసిన వారి పేరు లేదు",
		ENROLL : "నమోదు కండి",
		VIEW_ONGOING_BATCHES : "జరుగుతున్న బ్యాచులు చూడండి",
		VIEW_UPCOMING_BATCHES : "రాబోతున్న బ్యాచులు చూడండి",
		USER_NAME_PROFILE : "వాడకందారు పేరు",
		BATCHES_FOR_THIS_COURSE : "ఈ కోర్సుకు సంబంధించిన బ్యాచులు",
		ERROR_EMPTY_FIELDS : "వివరాలు ఇవ్వండి",
		INVALID_CONTENT : "కంటెంటు సరిగా లేదు",
		TIME_OUT : "సర్వర్ ఎక్కువ సమయం తీసుకుంటోంది. తరువాత మళ్ళీ ప్రయత్నించండి",
		OPTIONAL : "ఐచ్ఛికము",
		PERCENTAGE : "శాతం",
		SUBJECTS : "పాఠ్యాంశాలు",
		FROM : "మొదలు తేదీ",
		TO : "చివరి తేదీ",
		SELECT_DATE : "తేదీ ఇవ్వండి",
		SAVE : "సేవ్ చెయ్యండి",
		GRADE : "తరగతి",
		INSTUTUION_NAME : "సంస్థ పేరు",
		BOARD_UNIVERSITY : "బోర్డు/విశ్వవిద్యాలయం",
		APPLY : "ఫిల్టర్ చెయ్యండి",
		MY_COMMUNITIES : "నా కమ్యూనిటీలు",
		AVAILABLE_FILTERS : "ఉన్న ఫిల్టర్లు",
		DISMISS : "రద్దు చెయ్యండి",
		NO_FILTERS_SELECTED : "ఫిల్టర్ ఎన్నుకోలేదు",
		ACCOMPLISHMENTS : "సాధించిన ఫలితాలు",
		ADD : "కలుపు",
		PERSONAL_DETAILS : "వ్యక్తిగత వివరాలు",
		AFFILIATIONS : "అనుబంధాలు",
		SHOW_LESS : "తక్కువ చూపించు",
		SHOW_MORE : "ఇంకా చూపించు",
		USERNAME : "వాడకందారు పేరు",
		YOUR_PROFILE_IS : "మీ ప్రొఫైలు",
		FOLLOW : "అనుసరించండి",
		PEOPLE_YOU_FOLLOW : "మీరు అనుసరిస్తున్న వ్యక్తులు",
		GROUPS_YOU_FOLLOW : "మీరు అనుసరిస్తున్నగుంపులు",
		PEOPLE_WHO_FOLLOW_YOU : "మిమ్మల్ని అనుసరిస్తున్న వ్యక్తులు",
		SKILL_TAGS : "నైపుణ్యపు గుర్తులు",
		ENDORSE : "ఆమోదించండి",
		MODULE_NAME : "మాడ్యూల్ పేరు",
		NIL : "ఏమీ లేదు",
		PINNED_BY_ADMIN : "నిర్వాహకుడు పిన్ చేసినది",
		READ_MORE : "ఇంకా చదవండి...",
		THIS_IS_A_RESTRICTED_COMMUNITY : "ఇది కొందరికే పరిమితమైన కమ్యూనిటీ",
		DOWNLOAD_CONFIRMATION_TEXT : "డౌన్‌లోడ్ చెయ్యాలా?",
		YES : "అవును",
		NO : "కాదు",
		ABOUT_MODULE : "ఈ మాడ్యూల్ గురించి",
		COMMING_SOON : "త్వరలో...",
		TITLE_EDUCATION : "ఎడ్యుకేషన్",
		TITLE_EXPERIENCES : "అనుభవాలు",
		TITLE_ADDRESS : "చిరునామా",
		LAST_NAME : "చివరి పేరు",
		LAST_NAME_HINT : "మీ చివరి పేరును నమోదు చేయండి",
		NAME : "పేరు",
		NAME_HINT : "మీ పేరు రాయుము, మీ పేరు రాయండి",
		GENDER : "లింగం",
		DATE_OF_BIRTH : "పుట్టిన తేది",
		CURRENT_LOCATION : "ప్రస్తుత స్తలం",
		HINT_CURRENT_LOCATION : "మీ స్థానాన్ని నమోదు చేయండి",
		MODULES : "విభాగములు",
		BTN_CLICK_TO_OPEN_CONTENT : "కంటెంట్ను తెరవడానికి క్లిక్ చేయండి",
		NO_CHANGE : "మార్పులు చేయలేదు",
		START_COURSE : "కోర్సు ప్రారంభం",
		ERROR_INVALID_AADHAAR : "దయచేసి ఆధార్ నంబర్ ఆకృతిని తనిఖీ చేయండి",
		ERROR_CANT_SHARE_TRY_AGAIN : "భాగస్వామ్యం చేయలేరు, మళ్లీ ప్రయత్నించండి",
		ERROR_BATCH_NOT_STARTED : "బ్యాచ్ ప్రారంభించబడలేదు",
		MSG_NO_NEW_NOTIFICATION : "కొత్త నోటిఫికేషన్ లేదు",
		MSG_NO_DETAILS_TO_SHOW : "చూపించడానికి వివరాలు ఏవీ లేవు",
		MSG_IMPORTED_SUCCESSFULLY : "విజయవంతంగా దిగుమతి అయింది",
		ERROR_CANT_OPEN_EMPTY_CONTENT : "ఖాళీ కంటెంట్ను తెరవలేరు",
		ERROR_NO_BATCHES_FOUND : "ఏ బ్యాచ్లు కనుగొనబడలేదు",
		ANSWER : "సమాధానం",
		BTN_SUBMIT : "సమర్పించండి",
		TOPIC_YOU_MIGHT_LIKE : "మీరు ఇష్టపడే విషయము",
		OPEN_SETTINGS : "ఓపెన్ సెట్టింగులు",
		PERMISSION_NOT_AVAILABLE : "అనుమతి పొందని అనుమతి",
		LABEL_ADD_A_SKILL : "నైపుణ్యాన్ని జోడించండి",
		TYPE_TO_ADD_A_SKILL : "నైపుణ్యాన్ని జోడించడానికి టైప్ చేయండి",
		ERROR_ALREADY_ADDED : "ఇప్పటికే జోడించబడింది",
		WARNING_PLEASE_ADD_MANDATORY_DETAILS : "దయచేసి తప్పనిసరి వివరాలు జోడించండి",
		WARNING_PLEASE_MAKE_SOME_CHANGES : "దయచేసి కొంత మార్పు చేయండి",
		WARNING_INVALID_YEAR_OF_PASSING : "చెల్లుబాటులో లేని సంవత్సరం",
		WARNING_INVALID_PERCENTAGE : "చెల్లని శాతం",
		WARNING_INVALID_GRADE : "చెల్లని గ్రేడ్",
		DEGREE : "డిగ్రీ",
		INSTITUTION_NAME : "ఇన్స్ట్రుమెంట్ పేరు",
		IS_THIS_YOUR_CURRENT_JOB : "ఇది మీ ప్రస్తుత ఉద్యోగమా?",
		ERROR_MULTIPLE_CURRENT_JOB : "మీకు ఇప్పటికే ఉద్యోగం ఉంది, దయచేసి ప్రస్తుత ఉద్యోగం కాదు అని మార్చండి",
		OPTION_INAPPROPRIATE_CONTENT : "అనుచితమైన కంటెంట్",
		OPTION_COPYRIGHT_VIOLATION : "కాపీరైట్ ఉల్లంఘన",
		OPTION_PRIVACY_VIOLATION : "గోప్యతా ఉల్లంఘన",
		OPTION_OTHER : "ఇతర",
		MODULE_NAME : "మాడ్యూల్ పేరు",
		CURRENT_LOCATION : "ప్రస్తుత స్తలం",
		HOBBIES : "అభిరుచులు",
		EDIT_PROFILE : "ప్రొఫైల్ను సవరించండి",
		ACTIVE : "క్రియాశీల",
		STORAGE : "నిల్వ నిరాకరించబడింది",
		PERMISSION_DENIED : "అనుమతి నిరాకరించబడింది",
		YEAR_OF_PASSING : "ప్రయాణిస్తున్న సంవత్సరం",
		SELECT_ADDRESS_TYPE : "చిరునామా రకాన్ని ఎంచుకోండి",
		LANGUAGES : "భాషలు",
		EMAIL : "ఇమెయిల్",
		CHANGE_LANGUAGE : "భాష మార్చు",
		////
		ERROR_NO_RESUME_CONTENT_AVAILABLE : "కంటెంట్ పునఃప్రారంభం అందుబాటులో లేనందున",
		CANCEL : "రద్దు",
		SELECT_LANGUAGE : "భాషను ఎంచుకోండి",
		READ_LESS : "తక్కువ చదవండి",
		CONFIRM_DEL : "తొలగించాలా?",
		ADDRESS_LINE1 : "చిరునామా పంక్తి 1",
		ADDRESS_LINE2 : "చిరునామా లైన్ 2",
		CITY : "సిటీ",
		STATE : "రాష్ట్రం",
		COUNTRY : "దేశం",
		PINCODE : "పిన్ కోడ్",
		PERMANENT : "శాశ్వత",
		CURRENT : "ప్రస్తుత",
		JOB_NAME : "ఉద్యోగ పేరు",
		ORGANIZATION : "సంస్థ",
		POSITION : "స్థానం",
		CHOOSE_FROM_FOLLOWING : "కింది నుండి ఎంచుకోండి"
	},
	"bn_IN" : {
	},
	"ml_IN" : {
		ALREADY_HAVE_ACC : "ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ? ഇപ്പോൾ സൈൻ ഇൻ ചെയ്യുക",
		APPLY_FILTER : "ഫിൽട്ടർ പ്രയോഗിക്കുക",
		AS_FILE : "ഫയൽ പോലെ",
		AS_LINK : "ലിങ്ക് ആയി",
		BACK_TO_EXIT : "അപ്ലിക്കേഷൻ അവസാനിപ്പിക്കാൻ വീണ്ടും മടങ്ങുക",
		CANCEL_DOWNLOAD : "ക്യാൻലൽ ഡൌൺലോഡ് ചെയ്യുക",
		COMING_SOON : "ഉടൻ വരുന്നു..",
		COMMUNITIES : "കമ്മ്യൂണിറ്റികൾ",
		CONFIRM : "സ്ഥിരീകരിക്കുക",
		COURSE : "കോഴ്സ്",
		COURSE_ENROLLED : "പഠന കോഴ്സ്",
		COURSE_PROGRESS_COMPLETED : "% s% പൂർത്തിയായി",
		CONTENT_FLAGGED_MSG : "ഉള്ളടക്കം വിജയകരമായി ഫ്ലാഗുചെയ്തു",
		CONTENT_FLAG_FAIL : "ഉള്ളടക്ക ഫ്ലാഗുചെയ്യൽ പരാജയപ്പെട്ടു",
		COURSES_BNAV : "കോഴ്സുകൾ",
		COURSES_IN_PROGRESS : "കോഴ്സുകൾ പുരോഗതിയിലാണ്",
		COURSES_LW : "കോഴ്സുകൾ",
		CREATED_BY : "ഉണ്ടാക്കിയത്",
		DELETE : "ഇല്ലാതാക്കുക",
		DESCRIPTION : "വിവരണം",
		DOWNLOAD : "ഡൗൺലോഡ് ചെയ്യുക",
		DOWNLOADS : "ഡൌൺലോഡുകൾ",
		EDIT : "എഡിറ്റുചെയ്യുക",
		EMAIL_ID : "ഇ - മെയിൽ ഐഡി",
		EMPTY_SEARCH_RESULTS : "തിരയൽ ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല",
		ENROLL_COURSE : "ഈ കോഴ്സ് എൻറോൾ ചെയ്യുക",
		ERROR_CONTENT_NOT_AVAILABLE : "ഉള്ളടക്കം ലഭ്യമല്ല",
		ERROR_CONTENT_NOT_FOUND : "ഉള്ളടക്കം ഇനിയും ചേർത്തില്ല",
		ERROR_DURATION_NOT_AVAILABLE : "ദൈർഘ്യം ലഭ്യമല്ല",
		ERROR_EMAIL_FORMAT : "ഇമെയിൽ ഫോർമാറ്റ് ശരിയാണ്",
		ERROR_EMPTY_EMAIL : "ദയവായി ഇമെയിൽ നൽകുക",
		ERROR_EMPTY_FIRSTNAME : "പേര് നൽകുക",
		ERROR_EMPTY_LANGUAGE : "ദയവായി ചുരുങ്ങിയത് ഒരു ഭാഷ തിരഞ്ഞെടുക്കുക",
		ERROR_EMPTY_MOBILE : "ദയവായി മൊബൈൽ നമ്പർ നൽകുക",
		ERROR_EMPTY_PASSWORD : "ദയവായി പാസ്വേഡ് നൽകുക",
		ERROR_EMPTY_USERNAME : "ദയവായി ഉപയോക്തൃ നാമം നൽകുക",
		ERROR_FETCHING_DATA : "ഡാറ്റ ലഭ്യമാക്കുന്നതിൽ പിശക്",
		ERROR_NO_COURSES_ENROLLED : "ഇതുവരെ കോഴ്സുകൾ ഇതുവരെ എൻറോൾ ചെയ്തിട്ടില്ല",
		ERROR_OFFLINE_MODE : "നിങ്ങൾ ഇന്റർനെറ്റിൽ കണക്റ്റുചെയ്തിട്ടില്ല.",
		ERROR_NO_OFFLINE_RESOURCE : "ഓഫ്ലൈൻ ഉറവിടം ഇതുവരെ ഇല്ല",
		ERROR_SERVER_CONNECTION : "സെർവറിലേക്ക് ബന്ധിപ്പിക്കാൻ കഴിയുന്നില്ല",
		ERROR_SERVER_MESSAGE : "പിശക്:",
		ERROR_SHORT_MOBILE : "ദയവായി മൊബൈൽ നമ്പർ ഫോർമാറ്റ് പരിശോധിക്കുക",
		ERROR_SHORT_PASSWORD : "പാസ്വേഡ് 8 പ്രതീകങ്ങളേക്കാൾ ചെറുതായിരിക്കരുത്",
		FETCHING_CONTENTS : "ലഭ്യമാക്കുന്ന ഉള്ളടക്കങ്ങൾ:% s%",
		FILE_SIZE : "വലുപ്പം [% s]",
		FILTER : "ഫിൽറ്റർ ചെയ്യുക",
		FILTER_BY : "ഫിൽട്ടർ ബൈ",
		FIRST_NAME : "പേരിന്റെ ആദ്യഭാഗം",
		FIRST_NAME_HINT : "നിങ്ങളുടെ ആദ്യ പേര് നൽകുക",
		GROUPS : "ഗ്രൂപ്പുകൾ",
		GROUPS_BNAV : "ഗ്രൂപ്പുകൾ",
		HINT_EMAIL_ID : "sample@test.com",
		HINT_LANGUAGE : "മുൻകൂട്ടി തയ്യാറാക്കിയ ഭാഷ തിരഞ്ഞെടുക്കുക",
		HINT_MOBILE_NUMBER : "മൊബൈൽ നമ്പർ നൽകുക",
		HINT_PASSWORD : "കുറഞ്ഞത് 8 പ്രതീകങ്ങളുള്ള പാസ്വേഡ്",
		HINT_USER_NAME : "ഉപയോക്തൃ നാമം നൽകുക",
		HOME_BNAV : "ഹോം",
		JOIN : "ചേരുക",
		LATEST_COURSES : "പുതിയ കോഴ്സുകൾ",
		LOADING_CONTENT : "ഉള്ളടക്കം ലോഡുചെയ്യുന്നു",
		LOGGED_OUT : "ലോഗ് ഔട്ട് ചെയ്തു",
		MOBILE_NUMBER : "മൊബൈൽ നമ്പർ",
		MODULE_SIZE : "മൊഡ്യൂൾ വലുപ്പം% s",
		MODULE_SIZE_UNAVAILABLE : "മൊഡ്യൂൾ വലുപ്പം ലഭ്യമല്ല",
		NEW : "പുതിയത്",
		NO_ACC_YET : "ഇതുവരെ അക്കൗണ്ട് ഇല്ലേ? ഇപ്പോൾ സൈൻ അപ്പ് ചെയ്യുക",
		NO_PREVIEW : "പ്രിവ്യൂ ഒന്നും ലഭ്യമല്ല",
		NUMBER_OF_VOTES : "വോട്ടുകളുടെ എണ്ണം",
		OPEN : "തുറക്കുക",
		PASSWORD : "password",
		PHONE : "ഫോൺ",
		PLAY : "കളിക്കുക",
		POPULAR_COURSES : "ജനപ്രിയ കോഴ്സുകൾ",
		PREVIEWS : "പ്രിവ്യൂകൾ",
		PROFILE_BNAV : "പ്രൊഫൈൽ",
		PROFILE_DETAILS_TITLE : "പ്രൊഫൈൽ വിശദാംശങ്ങൾ",
		PROFILE_LW : "പ്രൊഫൈൽ",
		PUBLISHED_DATE : "പ്രസിദ്ധീകരിച്ച തീയതി",
		QUIZ : "ക്വിസ്",
		RESOURCES_BNAV : "റിസോർസുകൾ",
		RESOURCES_LW : "വിഭവങ്ങൾ",
		RESUME : "പുനരാരംഭിക്കുക",
		RETRY_ACTION : "വീണ്ടും ശ്രമിക്കുക",
		SAVED_ON : "സംരക്ഷിച്ചു",
		SAVED_RESOURCES : "സംരക്ഷിച്ച വിഭവങ്ങൾ",
		SEARCH_HINT : "തിരയുക",
		SELECT : "തിരഞ്ഞെടുക്കുക",
		SELECT_A_REASON : "ഒരു കാരണം തിരഞ്ഞെടുക്കുക",
		SERVER_CONNECTION_ERROR : "സെർവറിലേക്ക് ബന്ധിപ്പിക്കാൻ കഴിയുന്നില്ല",
		SHARE_THIS : "ഇത് പങ്കുവയ്ക്കുക",
		SIGN_IN : "സൈൻ ഇൻ",
		SIGN_UP : "സൈൻ അപ്പ് ചെയ്യുക",
		SORT_BY : "ഇങ്ങനെ അടുക്കുക",
		SPLASH_MESSAGE : "പ്രോജക്ട് എൻ.സി.റ്റി.ഇ",
		STRUCTURE : "ഘടന",
		TO_DO : "ചെയ്യാൻ",
		USER_NAME : "ഉപയോക്തൃ നാമം",
		VIEW_ALL : "എല്ലാം കാണൂ",
		VIEW_ALL_COMMUNITIES : "നിങ്ങൾ ഭാഗമായിട്ടാണ് എല്ലാ കമ്മ്യൂണിറ്റികളും കാണുന്നത്",
		VIEW_MORE : "കൂടുതൽ കാണു",
		WAIT_REQUEST : "കാത്തിരിക്കൂ ...",
		WELCOME_BACK : "തിരികെ മടങ്ങുക %s",
		WELCOME_M1 : "NTP- ലേക്ക് സ്വാഗതം",
		WELCOME_M2 : "അധ്യാപകർക്കായി ഘടനാപരമായ വിദ്യാഭ്യാസം",
		WELCOME_ON_BOARD : "NTP- ലേക്ക് സ്വാഗതം,% s",
		WHAT_WENT_WRONG : "എന്താണ് തെറ്റിയത്?",
		YOUR_PROGRESS : "നിങ്ങളുടെ പുരോഗതി:% s%",
		FLAG : "ഫ്ലാഗുചെയ്യുക / റിപ്പോർട്ടുചെയ്യുക",
		ERROR_EMPTY_RESULT : "ഫലമൊന്നും ലഭ്യമല്ല",
		ERROR_FLAG_CONTENT_MIN_REASON : "ഉള്ളടക്കം ഫ്ലാഗുചെയ്യുന്നതിന് ദയവായി ഒരു കാരണം തിരഞ്ഞെടുക്കൂ",
		ERROR_INVALID_EMAIL : "അസാധുവായ ഇമെയിൽ ഐഡി",
		MSG_RESOURCE_DELETED : "ഉപകരണത്തിൽ നിന്ന് ഉള്ളടക്കം ഇല്ലാതാക്കി",
		LOGOUT : "പുറത്തുകടക്കുക",
		CREATOR_NAME_NOT_AVAILABLE : "സ്രഷ്ടാവിന്റെ പേര് ലഭ്യമല്ല",
		ENROLL : "എൻറോൾ ചെയ്യുക",
		VIEW_ONGOING_BATCHES : "നിലവിലുള്ള ബാച്ചുകൾ കാണുക",
		VIEW_UPCOMING_BATCHES : "വരാനിരിക്കുന്ന ബാച്ചുകൾ കാണുക",
		USER_NAME_PROFILE : "ഉപയോക്തൃ നാമം",
		BATCHES_FOR_THIS_COURSE : "ഈ കോഴ്സിനുള്ള ടേബിൾസ്",
		ERROR_EMPTY_FIELDS : "ദയവായി detials നൽകുക.",
		INVALID_CONTENT : "അസാധുവായ ഉള്ളടക്കം",
		TIME_OUT : "സെർവർ കാലഹരണപ്പെട്ടു, പിന്നീട് വീണ്ടും ശ്രമിക്കുക",
		OPTIONAL : "(ഓപ്ഷണൽ)",
		PERCENTAGE : "ശതമാനം",
		SUBJECTS : "വിഷയങ്ങൾ",
		FROM : "മുതൽ",
		TO : "ലേക്ക്",
		SELECT_DATE : "തീയതി തിരഞ്ഞെടുക്കുക",
		SAVE : "രക്ഷിക്കും",
		GRADE : "ഗ്രേഡ്",
		INSTUTUION_NAME : "ഇൻസ്റ്റൻഷൻ പേര്",
		BOARD_UNIVERSITY : "ബോർഡ് / യൂണിവേഴ്സിറ്റി",
		APPLY : "പ്രയോഗിക്കുക",
		MY_COMMUNITIES : "എന്റെ കമ്മ്യൂണിറ്റികൾ",
		AVAILABLE_FILTERS : "ലഭ്യമായ ഫിൽട്ടറുകൾ",
		DISMISS : "നിരാകരിക്കുക",
		NO_FILTERS_SELECTED : "ഫിൽട്ടർ തിരഞ്ഞെടുത്തിട്ടില്ല",
		ACCOMPLISHMENTS : "നേട്ടങ്ങൾ",
		ADD : "ചേർക്കുക",
		PERSONAL_DETAILS : "വ്യക്തിഗത വിശദാംശങ്ങൾ",
		AFFILIATIONS : "അഫിലിയേഷൻ",
		SHOW_LESS : "കുറച്ച് കാണിക്കുക",
		SHOW_MORE : "കൂടുതൽ കാണിക്കുക",
		CREATOR_OF : "സ്രഷ്ടാവ്",
		USERNAME : "ഉപയോക്തൃനാമം",
		YOUR_PROFILE_IS : "നിങ്ങളുടെ പ്രൊഫൈൽ ആണ്",
		FOLLOW : "പിന്തുടരുക",
		PEOPLE_YOU_FOLLOW : "നിങ്ങൾ പിന്തുടരുന്ന ആളുകൾ",
		GROUPS_YOU_FOLLOW : "നിങ്ങൾ പിന്തുടരുന്ന ഗ്രൂപ്പുകൾ",
		PEOPLE_WHO_FOLLOW_YOU : "നിന്നെ പിന്തുടരുന്ന ആളുകൾ",
		SKILL_TAGS : "കഴിവുള്ള ടാഗുകൾ",
		ENDORSE : "അംഗീകരിക്കുക",
		MODULE_NAME : "മോഡൽ പേര്",
		NIL : "ഇല്ല",
		PINNED_BY_ADMIN : "അഡ്മിൻ കൊണ്ട് പിൻ ചെയ്തു",
		READ_MORE : "കൂടുതല് വായിക്കുക",
		THIS_IS_A_RESTRICTED_COMMUNITY : "ഇതൊരു നിയന്ത്രിത കമ്മ്യൂണിറ്റി ആണ്",
		DOWNLOAD_CONFIRMATION_TEXT : "നിങ്ങൾക്ക് ഡൌൺലോഡ് ചെയ്യണോ?",
		YES : "അതെ",
		NO : "ഇല്ല",
		ABOUT_MODULE : "ഈ ഘടനയെക്കുറിച്ച്",
		COMMING_SOON : "ഉടൻ വരുന്നു",
		TITLE_EDUCATION : "വിദ്യാഭ്യാസം",
		TITLE_EXPERIENCES : "അനുഭവങ്ങൾ",
		TITLE_ADDRESS : "വിലാസം",
		LAST_NAME : "പേരിന്റെ അവസാന ഭാഗം",
		LAST_NAME_HINT : "നിങ്ങളുടെ അവസാന നാമം നൽകുക",
		NAME : "പേര്",
		NAME_HINT : "നിങ്ങളുടെ പേര് നൽകുക",
		GENDER : "ലിംഗഭേദം",
		DATE_OF_BIRTH : "ജനിച്ച ദിവസം",
		CURRENT_LOCATION : "ഇപ്പോഴുള്ള സ്ഥലം",
		HINT_CURRENT_LOCATION : "നിങ്ങളുടെ സ്ഥാനം നൽകുക",
		MODULES : "ഘടകങ്ങൾ",
		BTN_CLICK_TO_OPEN_CONTENT : "ഉള്ളടക്കം തുറക്കാൻ ക്ലിക്കുചെയ്യുക",
		NO_CHANGE : "മാറ്റങ്ങളൊന്നും വരുത്തിയിട്ടില്ല",
		START_COURSE : "കോഴ്സ് ആരംഭിക്കുക",
		ERROR_INVALID_AADHAAR : "ദയവായി ആധാർ നമ്പർ ഫോർമാറ്റ് പരിശോധിക്കുക",
		ERROR_CANT_SHARE_TRY_AGAIN : "പങ്കിടാൻ കഴിയില്ല, വീണ്ടും ശ്രമിക്കുക",
		ERROR_BATCH_NOT_STARTED : "ബാച്ച് ആരംഭിച്ചിട്ടില്ല",
		MSG_NO_NEW_NOTIFICATION : "പുതിയ അറിയിപ്പ് ഒന്നുമില്ല",
		MSG_NO_DETAILS_TO_SHOW : "കാണിക്കുന്നതിന് വിശദാംശങ്ങളൊന്നുമില്ല",
		MSG_IMPORTED_SUCCESSFULLY : "ഇറക്കുമതിചെയ്തു",
		ERROR_CANT_OPEN_EMPTY_CONTENT : "ശൂന്യമായ ഉള്ളടക്കം തുറക്കാൻ കഴിയില്ല",
		ERROR_NO_BATCHES_FOUND : "ബാച്ചുകളൊന്നും കണ്ടെത്തിയില്ല",
		ANSWER : "ഉത്തരം",
		BTN_SUBMIT : "സമർപ്പിക്കുക",
		TOPIC_YOU_MIGHT_LIKE : "നിങ്ങൾ ഇഷ്ടപ്പെട്ടേക്കാവുന്ന വിഷയങ്ങൾ",
		OPEN_SETTINGS : "ക്രമീകരണങ്ങൾ തുറക്കുക",
		PERMISSION_NOT_AVAILABLE : "അനുവദനീയമല്ല",
		LABEL_ADD_A_SKILL : "ഒരു വൈദഗ്ദ്ധ്യം ചേർക്കുക",
		TYPE_TO_ADD_A_SKILL : "ഒരു കഴിവ് ചേർക്കാൻ ടൈപ്പുചെയ്യുക",
		ERROR_ALREADY_ADDED : "ഇതിനകം ചേർത്തു",
		WARNING_PLEASE_ADD_MANDATORY_DETAILS : "നിർബന്ധിത വിവരങ്ങൾ ചേർക്കുക",
		WARNING_PLEASE_MAKE_SOME_CHANGES : "ദയവായി ചില മാറ്റങ്ങൾ വരുത്തുക",
		WARNING_INVALID_YEAR_OF_PASSING : "അസാധുവായ പാസ് വേഡിംഗ്",
		WARNING_INVALID_PERCENTAGE : "അസാധുവായ ശതമാനം",
		WARNING_INVALID_GRADE : "അസാധുവായ ഗ്രേഡ്",
		DEGREE : "ഡിഗ്രി",
		INSTITUTION_NAME : "സ്ഥാപനത്തിന്റെ പേര്",
		IS_THIS_YOUR_CURRENT_JOB : "ഇത് നിങ്ങളുടെ നിലവിലെ ജോലിയാണോ?",
		ERROR_MULTIPLE_CURRENT_JOB : "നിങ്ങൾക്കൊരു നിലവിലുള്ള ജോലി ഇതിനകം ഉണ്ടെങ്കിൽ, അത് നിലവിലെ ജോലിയല്ലെന്ന് മാറ്റുക",
		OPTION_INAPPROPRIATE_CONTENT : "അനുചിതമായ ഉള്ളടക്കം",
		OPTION_COPYRIGHT_VIOLATION : "പകർപ്പവകാശ ലംഘനം",
		OPTION_PRIVACY_VIOLATION : "സ്വകാര്യത ലംഘനം",
		OPTION_OTHER : "മറ്റുള്ളവ",
		MODULE_NAME : "മൊഡ്യൂളിന്റെ പേര്",
		CURRENT_LOCATION : "ഇപ്പോഴുള്ള സ്ഥലം",
		HOBBIES : "ഹോബികൾ",
		EDIT_PROFILE : "പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യൂ",
		ACTIVE : "സജീവമാണ്",
		STORAGE : "സംഭരണം നിരസിച്ചു",
		PERMISSION_DENIED : "അനുമതി നിഷേധിച്ചു",
		YEAR_OF_PASSING : "കടന്നുപോകുന്ന വർഷം",
		SELECT_ADDRESS_TYPE : "വിലാസ തരം തിരഞ്ഞെടുക്കുക",
		LANGUAGES : "ഭാഷകൾ",
		EMAIL : "ഇ-മെയിൽ",
		CHANGE_LANGUAGE : "ഭാഷ മാറ്റുക",
	},
	"or_IN" : {
	},
	"gu_IN" : {
		ALREADY_HAVE_ACC : "પહેલેથી એકાઉન્ટ છે? હવે સાઇન ઇન કરો",
		APPLY_FILTER : "ફિલ્ટર લાગુ કરો",
		AS_FILE : "ફાઇલ તરીકે",
		AS_LINK : "લિંક તરીકે",
		BACK_TO_EXIT : "એપ્લિકેશનમાંથી બહાર નીકળવા માટે ફરી પાછા દબાવો",
		CANCEL_DOWNLOAD : "કન્સલ ડાઉનલોડ કરો",
		COMING_SOON : "ટૂક સમયમાં આવી રહ્યું છે..",
		COMMUNITIES : "સમુદાયો",
		CONFIRM : "પુષ્ટિ કરો",
		COURSE : "અભ્યાસક્રમ",
		COURSE_ENROLLED : "કોર્સમાં પ્રવેશ",
		COURSE_PROGRESS_COMPLETED : "% s% પૂર્ણ થયું",
		CONTENT_FLAGGED_MSG : "સામગ્રી સફળતાપૂર્વક ફ્લેગ કરવામાં આવી છે",
		CONTENT_FLAG_FAIL : "સામગ્રી ફ્લેગિંગ નિષ્ફળ",
		COURSES_BNAV : "અભ્યાસક્રમો",
		COURSES_IN_PROGRESS : "પ્રગતિમાં અભ્યાસક્રમો",
		COURSES_LW : "અભ્યાસક્રમો",
		CREATED_BY : "દ્વારા બનાવવામાં",
		DELETE : "કાઢી નાંખો",
		DESCRIPTION : "વર્ણન",
		DOWNLOAD : "ડાઉનલોડ કરો",
		DOWNLOADS : "ડાઉનલોડ્સ",
		EDIT : "સંપાદિત કરો",
		EMAIL_ID : "ઇમેઇલ આઈડી",
		EMPTY_SEARCH_RESULTS : "કોઈ શોધ પરિણામો મળ્યાં નથી",
		ENROLL_COURSE : "આ કોર્સમાં પ્રવેશ કરો",
		ERROR_CONTENT_NOT_AVAILABLE : "સામગ્રી ઉપલબ્ધ નથી",
		ERROR_CONTENT_NOT_FOUND : "અનુક્રમણિકાઓ હજુ સુધી ઉમેરાતાં નથી",
		ERROR_DURATION_NOT_AVAILABLE : "સમયગાળો ઉપલબ્ધ નથી",
		ERROR_EMAIL_FORMAT : "ઇમેઇલ ફોર્મેટ યોગ્ય નથી",
		ERROR_EMPTY_EMAIL : "કૃપા કરીને ઇમેઇલ દાખલ કરો",
		ERROR_EMPTY_FIRSTNAME : "કૃપા કરીને નામ દાખલ કરો",
		ERROR_EMPTY_LANGUAGE : "કૃપા કરીને ઓછામાં ઓછી એક ભાષા પસંદ કરો",
		ERROR_EMPTY_MOBILE : "કૃપા કરીને મોબાઇલ નંબર દાખલ કરો",
		ERROR_EMPTY_PASSWORD : "પાસવર્ડ દાખલ કરો",
		ERROR_EMPTY_USERNAME : "વપરાશકર્તા નામ દાખલ કરો",
		ERROR_FETCHING_DATA : "ડેટા લાવવામાં ભૂલ",
		ERROR_NO_COURSES_ENROLLED : "કોઈ અભ્યાસક્રમો હજુ સુધી પ્રવેશ નથી",
		ERROR_OFFLINE_MODE : "તમે ઇન્ટરનેટથી જોડાયેલા નથી",
		ERROR_NO_OFFLINE_RESOURCE : "હજી કોઈ ઑફલાઇન સ્રોત નથી",
		ERROR_SERVER_CONNECTION : "સર્વર સાથે કનેક્ટ કરવામાં અસમર્થ",
		ERROR_SERVER_MESSAGE : "ભૂલ:",
		ERROR_SHORT_MOBILE : "કૃપા કરીને મોબાઇલ નંબર ફોર્મેટ તપાસો",
		ERROR_SHORT_PASSWORD : "પાસવર્ડ 8 અક્ષરો કરતા ટૂંકા ન હોઈ શકે",
		FETCHING_CONTENTS : "આનયન સામગ્રી:% s%",
		FILE_SIZE : "કદ [% s]",
		FILTER : "ફિલ્ટર",
		FILTER_BY : "દ્વારા ફિલ્ટર",
		FIRST_NAME : "પ્રથમ નામ",
		FIRST_NAME_HINT : "તમારું પ્રથમ નામ દાખલ કરો",
		GROUPS : "જૂથો",
		GROUPS_BNAV : "જૂથો",
		HINT_EMAIL_ID : "sample@test.com",
		HINT_LANGUAGE : "પસંદ કરેલી ભાષા પસંદ કરો",
		HINT_MOBILE_NUMBER : "મોબાઇલ નંબર દાખલ કરો",
		HINT_PASSWORD : "ન્યૂનતમ 8 અક્ષર પાસવર્ડ",
		HINT_USER_NAME : "વપરાશકર્તા નામ દાખલ કરો",
		HOME_BNAV : "હોમ",
		JOIN : "જોડાઓ",
		LATEST_COURSES : "તાજેતરના અભ્યાસક્રમો",
		LOADING_CONTENT : "સામગ્રી લોડ કરી રહ્યું છે",
		LOGGED_OUT : "લૉગ આઉટ થયું",
		MOBILE_NUMBER : "મોબાઇલ નંબર",
		MODULE_SIZE : "મોડ્યુલ કદ% s",
		MODULE_SIZE_UNAVAILABLE : "મોડ્યુલ કદ અનુપલબ્ધ છે",
		NEW : "નવું",
		NO_ACC_YET : "હજી કોઈ એકાઉન્ટ નથી? અત્યારે જોડવ",
		NO_PREVIEW : "પૂર્વાવલોકન ઉપલબ્ધ નથી",
		NUMBER_OF_VOTES : "મતોની સંખ્યા",
		OPEN : "ખોલો",
		PASSWORD : "પાસવર્ડ",
		PHONE : "ફોન",
		PLAY : "રમવા",
		POPULAR_COURSES : "લોકપ્રિય અભ્યાસક્રમો",
		PREVIEWS : "પૂર્વાવલોકન",
		PROFILE_BNAV : "પ્રોફાઇલ",
		PROFILE_DETAILS_TITLE : "પ્રોફાઇલ વિગતો",
		PROFILE_LW : "પ્રોફાઇલ",
		PUBLISHED_DATE : "પ્રકાશિત તારીખ",
		QUIZ : "ક્વિઝ",
		RESOURCES_BNAV : "સ્રોતો",
		RESOURCES_LW : "સંપત્તિ",
		RESUME : "ફરી શરુ કરવું",
		RETRY_ACTION : "કૃપા કરીને ફરી પ્રયાસ કરો",
		SAVED_ON : "પર સાચવેલ",
		SAVED_RESOURCES : "સાચવેલા સાધનો",
		SEARCH_HINT : "શોધો",
		SELECT : "પસંદ કરો",
		SELECT_A_REASON : "એક કારણ પસંદ કરો",
		SERVER_CONNECTION_ERROR : "સર્વર સાથે કનેક્ટ કરવામાં અસમર્થ",
		SHARE_THIS : "આ શેર કરો",
		SIGN_IN : "સાઇન ઇન કરો",
		SIGN_UP : "સાઇન અપ કરો",
		SORT_BY : "દ્વારા સૉર્ટ",
		SPLASH_MESSAGE : "પ્રોજેક્ટ એનસીટીઇ",
		STRUCTURE : "માળખું",
		TO_DO : "શું કરવું",
		USER_NAME : "વપરાશકર્તા નામ",
		VIEW_ALL : "બધુજ જુઓ",
		VIEW_ALL_COMMUNITIES : "તમે જે સમુદાયોનો ભાગ છો તે જોઈ રહ્યાં છો",
		VIEW_MORE : "વધારે જોવો",
		WAIT_REQUEST : "મહેરબાની કરી રાહ જુવો ...",
		WELCOME_BACK : "આપનું સ્વાગત છે બેકઅપ %s",
		WELCOME_M1 : "NTP માં સ્વાગત છે",
		WELCOME_M2 : "શિક્ષકો માટે સ્ટ્રક્ચર્ડ શિક્ષણ",
		WELCOME_ON_BOARD : "NTP માં સ્વાગત છે,% s",
		WHAT_WENT_WRONG : "ખોટું શું થયું?",
		YOUR_PROGRESS : "તમારી પ્રગતિ:% s%",
		FLAG : "ધ્વજ / રિપોર્ટ",
		ERROR_EMPTY_RESULT : "પરિણામ ઉપલબ્ધ નથી",
		ERROR_FLAG_CONTENT_MIN_REASON : "ધ્વજ સામગ્રી માટે ઓછામાં ઓછી એક કારણ પસંદ કરો",
		ERROR_INVALID_EMAIL : "અમાન્ય ઇમેઇલ-આઈડી",
		MSG_RESOURCE_DELETED : "ઉપકરણમાંથી કાઢી નાખેલી સામગ્રી",
		LOGOUT : "લૉગ આઉટ",
		CREATOR_NAME_NOT_AVAILABLE : "નિર્માતા નામ ઉપલબ્ધ નથી",
		ENROLL : "નોંધણી કરો",
		VIEW_ONGOING_BATCHES : "ચાલુ બૅચેસ જુઓ",
		VIEW_UPCOMING_BATCHES : "આગામી બૅચેસ જુઓ",
		USER_NAME_PROFILE : "વપરાશકર્તા નામ",
		BATCHES_FOR_THIS_COURSE : "આ કોર્સ માટે ગોઠવણ",
		ERROR_EMPTY_FIELDS : "કૃપા કરીને વિગતો દાખલ કરો.",
		INVALID_CONTENT : "અમાન્ય સામગ્રી",
		TIME_OUT : "સર્વર સમયસમાપ્તિ, કૃપા કરીને પછી ફરીથી પ્રયાસ કરો",
		OPTIONAL : "(વૈકલ્પિક)",
		PERCENTAGE : "ટકાવારી",
		SUBJECTS : "વિષયો",
		FROM : "પ્રતિ",
		TO : "માટે",
		SELECT_DATE : "તારીખ પસંદ કરો",
		SAVE : "સાચવો",
		GRADE : "ગ્રેડ",
		INSTUTUION_NAME : "સૂચના નામ",
		BOARD_UNIVERSITY : "બોર્ડ / યુનિવર્સિટી",
		APPLY : "લાગુ પડે છે",
		MY_COMMUNITIES : "મારા સમુદાયો",
		AVAILABLE_FILTERS : "ઉપલબ્ધ ફિલ્ટર્સ",
		DISMISS : "બરતરફ",
		NO_FILTERS_SELECTED : "કોઈ ફિલ્ટર પસંદ નથી",
		ACCOMPLISHMENTS : "સિદ્ધિઓ",
		ADD : "ઉમેરો",
		PERSONAL_DETAILS : "અંગત વિગતો",
		AFFILIATIONS : "સંલગ્નતા",
		SHOW_LESS : "ઓછી બતાવો",
		SHOW_MORE : "વધારે બતાવ",
		CREATOR_OF : "ના સર્જક",
		USERNAME : "વપરાશકર્તા નામ",
		YOUR_PROFILE_IS : "તમારી પ્રોફાઇલ છે",
		FOLLOW : "અનુસરો",
		PEOPLE_YOU_FOLLOW : "તમે અનુસરો છો તે લોકો",
		GROUPS_YOU_FOLLOW : "તમે અનુસરો છો તે જૂથો",
		PEOPLE_WHO_FOLLOW_YOU : "જે લોકો તમને અનુસરે છે",
		SKILL_TAGS : "કૌશલ ટૅગ્સ",
		ENDORSE : "સમર્થન",
		MODULE_NAME : "મોડ્યુલ નામ",
		NIL : "નિલ",
		PINNED_BY_ADMIN : "સંચાલક દ્વારા પિન કરેલા",
		READ_MORE : "વધુ વાંચો",
		THIS_IS_A_RESTRICTED_COMMUNITY : "આ પ્રતિબંધિત સમુદાય છે",
		DOWNLOAD_CONFIRMATION_TEXT : "શું તમે ડાઉનલોડ કરવા માંગો છો?",
		YES : "હા",
		NO : "ના",
		ABOUT_MODULE : "આ મોડ્યુલ વિશે",
		COMMING_SOON : "ટૂક સમયમાં આવી રહ્યું છે",
		TITLE_EDUCATION : "શિક્ષણ",
		TITLE_EXPERIENCES : "અનુભવો",
		TITLE_ADDRESS : "સરનામું",
		LAST_NAME : "છેલ્લું નામ",
		LAST_NAME_HINT : "તમારું છેલ્લું નામ દાખલ કરો",
		NAME : "નામ",
		NAME_HINT : "તમારું નામ દાખલ કરો",
		GENDER : "જાતિ",
		DATE_OF_BIRTH : "જન્મ તારીખ",
		CURRENT_LOCATION : "અત્યારની જ્ગ્યા",
		HINT_CURRENT_LOCATION : "તમારું સ્થાન દાખલ કરો",
		MODULES : "મોડ્યુલો",
		BTN_CLICK_TO_OPEN_CONTENT : "સામગ્રી ખોલવા માટે ક્લિક કરો",
		NO_CHANGE : "કોઈ ફેરફારો કરવામાં આવ્યા નથી",
		START_COURSE : "કોર્સ શરૂ",
		ERROR_INVALID_AADHAAR : "કૃપા કરીને એડર નંબર ફોર્મેટ તપાસો",
		ERROR_CANT_SHARE_TRY_AGAIN : "શેર કરી શકતા નથી, ફરી પ્રયાસ કરો",
		ERROR_BATCH_NOT_STARTED : "બેચ શરૂ થયું નથી",
		MSG_NO_NEW_NOTIFICATION : "કોઈ નવી સૂચના નથી",
		MSG_NO_DETAILS_TO_SHOW : "બતાવવા માટે કોઈ વિગતો નથી",
		MSG_IMPORTED_SUCCESSFULLY : "આયાત કરેલ સફળતાપૂર્વક",
		ERROR_CANT_OPEN_EMPTY_CONTENT : "ખાલી સામગ્રી ખોલી શકાતી નથી",
		ERROR_NO_BATCHES_FOUND : "કોઈ બૅચેસ મળી નથી",
		ANSWER : "જવાબ આપો",
		BTN_SUBMIT : "સબમિટ કરો",
		TOPIC_YOU_MIGHT_LIKE : "તમને ગમશે તે વિષય",
		OPEN_SETTINGS : "સેટિંગ્સ ખોલો",
		PERMISSION_NOT_AVAILABLE : "મંજૂરી ઉપલબ્ધ નથી",
		LABEL_ADD_A_SKILL : "કૌશલ્ય ઉમેરો",
		TYPE_TO_ADD_A_SKILL : "કુશળતા ઉમેરવા માટે લખો",
		ERROR_ALREADY_ADDED : "પહેલેથી ઉમેરાયેલ છે",
		WARNING_PLEASE_ADD_MANDATORY_DETAILS : "કૃપા કરીને ફરજિયાત વિગતો ઉમેરો",
		WARNING_PLEASE_MAKE_SOME_CHANGES : "કૃપા કરીને કેટલાક ફેરફાર કરો",
		WARNING_INVALID_YEAR_OF_PASSING : "પસાર થવાનો અમાન્ય વર્ષ",
		WARNING_INVALID_PERCENTAGE : "અમાન્ય ટકાવારી",
		WARNING_INVALID_GRADE : "અમાન્ય ગ્રેડ",
		DEGREE : "ડિગ્રી",
		INSTITUTION_NAME : "સૂચના નામ",
		IS_THIS_YOUR_CURRENT_JOB : "શું આ તમારી વર્તમાન નોકરી છે?",
		ERROR_MULTIPLE_CURRENT_JOB : "તમારી પાસે પહેલેથી જ વર્તમાન નોકરી છે, કૃપા કરી તેને વર્તમાન નોકરી ન કરો",
		OPTION_INAPPROPRIATE_CONTENT : "અયોગ્ય સામગ્રી",
		OPTION_COPYRIGHT_VIOLATION : "કૉપિરાઇટ ઉલ્લંઘન",
		OPTION_PRIVACY_VIOLATION : "ગોપનીયતા ઉલ્લંઘન",
		OPTION_OTHER : "અન્ય",
		MODULE_NAME : "મોડ્યુલ નામ",
		CURRENT_LOCATION : "અત્યારની જ્ગ્યા",
		HOBBIES : "રૂચિ અને શોખ",
		EDIT_PROFILE : "પ્રોફાઇલ સંપાદિત કરો",
		ACTIVE : "સક્રિય",
		STORAGE : "સંગ્રહ નકારી",
		PERMISSION_DENIED : "પરવાનગી નકારી",
		YEAR_OF_PASSING : "પસાર થવાનો વર્ષ",
		SELECT_ADDRESS_TYPE : "સરનામું પ્રકાર પસંદ કરો",
		LANGUAGES : "ભાષાઓ",
		EMAIL : "ઇમેઇલ",
		CHANGE_LANGUAGE : "ભાષા બદલો",
	},
	"kn_IN" : {
	},
	"as_IN" : {
	},
	"mr_IN" : {
	},
	"pa_IN" : {
	},
	"ur_IN" : {
	},
}

var decideString = function(){
	var val = window.__CurrentLanguage;
	var merged = {};
	return objectAssign({},merged,stringsRes["en_US"],stringsRes[val]);
}


var setLanguage = function(lang){
	window.__CurrentLanguage = lang;
	JBridge.setKey("languagePref",lang);
}


exports.setLanguage = setLanguage;
exports.strings = decideString;
exports.stringsRes = stringsRes;
