const objectAssign = require('object-assign');
const stringsRes = {
	"en_US" : {
		ABOUT_MODULE : "ABOUT THIS MODULE",
		ALREADY_HAVE_ACC : "Already have an Account? Sign in now",
		APPLY_FILTER : "APPLY FILTER",
		AS_FILE : "As File",
		AS_LINK : "As Link",
		ASSIGNMENT : "ASSIGNMENT",
		BACK_TO_EXIT : "Press back again to exit app",
		CANCEL_DOWNLOAD : "CANCEL DOWNLOAD",
		CHOOSE_FROM_FOLLOWING : "Choose from following",
		CHOOSE_TITLE : "Choose from the following",
		COMING_SOON : "Coming soon..",
		COMING_SOON : "More details coming soon ..",
		COMMING_SOON : "Comming Soon",
		COMMUNITIES : "Communities",
		CONFIRM : "Confirm",
		COURSE : "COURSE",
		COURSE_ENROLLED : "Course enrolled",
		COURSE_PROGRESS_COMPLETED : "%s % done",
		COURSES_BNAV : "COURSES",
		ERROR_EMPTY_FIELDS : "Please enter the detials.",
		COURSES_IN_PROGRESS : "Courses In Progress",
		COURSES_LW : "Courses",
		CREATED_BY : "CREATED BY",
		DELETE : "Delete",
		DESCRIPTION : "Description",
		DONE : "done",
		DOWNLOAD : "DOWNLOAD",
		DOWNLOAD_RESOURCE : "DOWNLOAD THIS RESOURCE",
		DOWNLOADS : "downloads",
		EDIT : "Edit",
		EMAIL_ID : "EMAIL ID",
		EMPTY_SEARCH_RESULTS : "No Search Results Found",
		ENROLL_COURSE : "ENROLL THIS COURSE",
		ERROR_CONTENT_NOT_AVAILABLE : "Content not available",
		ERROR_CONTENT_NOT_FOUND : "Contents not added yet",
		ERROR_DURATION_NOT_AVAILABLE : "Duration not available",
		ERROR_EMAIL_FORMAT : "Email format not correct",
		ERROR_EMPTY_EMAIL : "Please enter the email",
		ERROR_EMPTY_FIRSTNAME : "Please enter the name",
		ERROR_EMPTY_LANGUAGE : "Please choose atleast one language",
		ERROR_EMPTY_MOBILE : "Please enter the mobile number",
		ERROR_EMPTY_PASSWORD : "Please enter the password",
		ERROR_EMPTY_USERNAME : "Please enter the user name",
		ERROR_FETCHING_DATA : "Error Fetching Data",
		ERROR_INPUT_FORM : "Please check your inputs",
		ERROR_LAYOUT_NOT_PASSED : "Layout Not Passed",
		ERROR_NO_COURSES_ENROLLED : "No Courses enrolled yet",
		ERROR_NO_INTERNET_MESSAGE : "You’re not connected to the internet.",
		ERROR_NO_OFFLINE_RESOURCE : "No offline resource yet",
		ERROR_OFFLINE_MODE : "No internet. Offline Mode",
		ERROR_SERVER_CONNECTION : "Unable to connect to server",
		ERROR_SERVER_MESSAGE : "Error :",
		ERROR_SHORT_MOBILE : "Please check the mobile number format",
		ERROR_SHORT_PASSWORD : "Password cannot be shorter than 8 characters",
		FETCHING_CONTENTS : "Fetching Contents : %s %",
		FILE_SIZE : "Size [%s]",
		FILTER : "Filter",
		FILTER_BY : "FILTER BY",
		FIRST_NAME : "NAME",
		FIRST_NAME_HINT : "Enter your name",
		FLAGGED_CONTENT : "FLAGGED CONTENT",
		FLAGGED_CONTENT_MESSAGE : "Content flagged successfully.The creator and the admin will be notified to review the content.",
		FORGOT_PASSWORD : "FORGOT PASSWORD?",
		FORGOT_PASSWORD : "FORGOT PASSWORD?",
		GO_BACK : "GO BACK",
		GROUPS : "Groups",
		GROUPS_BNAV : "GROUPS",
		HINT_EMAIL_ID : "sample@test.com",
		HINT_LANGUAGE : "Choose preffered language",
		HINT_MOBILE_NUMBER : "Enter mobile number",
		HINT_PASSWORD : "Minimum 8 character password",
		HINT_USER_NAME : "Enter user name",
		HOME_BNAV : "HOME",
		INTERNET_ISSUE : "INTERNET CONNECTION ISSUE",
		JOIN : "JOIN",
		LANGUAGE : "LANGUAGE",
		LANGUAGES : "LANGUAGES",
		LATEST_COURSES : "Latest Courses",
		LOADING_CONTENT : "Loading content",
		LOGGED_OUT : "Logged out",
		MOBILE_NUMBER : "MOBILE NUMBER",
		MODULE_LABEL : "Module %s: %s ",
		MODULE_SIZE : "Module Size %s",
		MODULE_SIZE_UNAVAILABLE : "Module Size Unavailable",
		MORE : "more",
		NEW : "New",
		NO_ACC_YET : "No Account yet? Sign up now",
		NO_INTERNET : "No internet connectivity",
		NO_OFFLINE_RESOURCES : "No offline resources yet",
		NO_PREVIEW : "No preview available",
		NO_RATING : "Unrated",
		NO_VOTES : "No votes yet",
		NUMBER_OF_VOTES : "Number of votes",
		OPEN : "OPEN",
		PASSWORD : "PASSWORD",
		PHONE : "PHONE",
		PLAY : "PLAY",
		POPULAR_COURSES : "Popular Courses",
		PREVIEWS : "PREVIEWS",
		PROFILE_BNAV : "PROFILE",
		PROFILE_DETAILS_TITLE : "Profile Details",
		PROFILE_LW : "Profile",
		PUBLISHED_DATE : "Published date",
		PUBLISHED_DATE : "Published date",
		QUIZ : "QUIZ",
		RECOMMENDED : "Recommended",
		REMAINING : "remaining",
		RESOURCES_BNAV : "RESOURCES",
		RESOURCES_LW : "Resources",
		RESUME : "RESUME",
		RETRY_ACTION : "Please retry",
		SAVED_ON : "Saved on",
		SAVED_RESOURCES : "Saved Resources",
		SEARCH_HINT : "Search",
		SEARCH_LOADING_MESSAGE : "Loading Search Results Please Wait...",
		SELECT : "SELECT",
		SELECT_A_REASON : "SELECT A REASON",
		SERVER_CONNECTION_ERROR : "Unable to connect to server",
		SHARE_THIS : "Share this",
		SIGN_IN : "SIGN IN",
		SIGN_UP : "SIGN UP",
		SIGN_UP_SUCCESS : "Sign Up Completed",
		SIGN_UP_SUCCESS : "Sign Up Completed",
		SORT_BY : "SORT BY",
		SORT_BY : "SORT BY",
		SPLASH_MESSAGE : "Project NCTE",
		STAR_RATINGS : "Star ratings",
		STRUCTURE : "Structure",
		TO_DO : "To-Do",
		USER_NAME : "USER NAME",
		VIEW : "VIEW",
		VIEW_ALL : "VIEW ALL",
		VIEW_ALL_COMMUNITIES : "Viewing all communities you’re a part of",
		VIEW_MORE : "VIEW MORE",
		VOTES : "Votes",
		WAIT_REQUEST : "Please Wait ...",
		WELCOME : "Welcome",
		WELCOME : "WELCOME",
		WELCOME_BACK : "WELCOME BACK %s",
		WELCOME_M1 : "Welcome to Sunbird",
		WELCOME_M2 : "Structured education for the educators",
		WELCOME_ON_BOARD : "Welcome to Sunbird, %s ",
		WHAT_WENT_WRONG : "What went wrong?",
		YOUR_PROGRESS : "Your Progress: %s%",
		FLAG : "Flag / Report ",
		ERROR_EMPTY_RESULT : "No result available",
		ERROR_FLAG_CONTENT_MIN_REASON : "Please select atleast one reason for flag the content",
		ERROR_INVALID_EMAIL : "Invalid Email Id",
		MSG_RESOURCE_DELETED : "Content deleted from device",
		LOGOUT : "Logout",
		CREATOR_NAME_NOT_AVAILABLE : "Creator name not available",
		CHECK_BATCHES : "Check Batches",
		SHOW_BATCHES : "Show Batches",
		ENROLL : "ENROLL",
		VIEW_ONGOING_BATCHES : "View ongoing batches",
		VIEW_UPCOMING_BATCHES : "View upcoming batches",
		BATCHES_FOR_THIS_COURSE : "Batches for this course",
		SHOW_BATCHES : "SHOW BATCHES",
	},
	"hi_IN" : {
	},
	"ta_IN" : {
	},
	"te_IN" : {
	},
	"bn_IN" : {
	},
	"ml_IN" : {
	},
	"or_IN" : {
	},
	"gu_IN" : {
	},
	"kn_IN" : {
	},
	"as_IN" : {
	},
	"mr_IN" : {
	},
	"pa_IN" : {
	},
	"ur_IN" : {
	},
}

var decideString = function(){
	var val = window.__CurrentLanguage;
	var merged = {};
	return objectAssign({},merged,stringsRes["en_US"],stringsRes[val]);
}


var setLanguage = function(lang){
	window.__CurrentLanguage = lang;
	JBridge.setKey("languagePref",lang);
}


exports.setLanguage = setLanguage;
exports.strings = decideString;
exports.stringsRes = stringsRes;
